### ISSUE TITLE
Fix EXIF data for videos and images

### ISSUE THREAD

**Issue by actual-saurabh** [rtCamp/rtMedia#118]
This is especially for iOS. It records videos in the default orientation and saves how the image/video is rotated in the EXIF data.

Client applications are supposed to display media using this EXIF data. IE does this for videos by default.

We cannot depend on the client for doing this. We need to check uploaded media for such rotation and fix it before saving/creating attachments and meta data.

https://github.com/rtCamp/buddypress-media/issues/102

**Comment by deepakpogra** [comment]
Hi,

While uploading profile picture i am able to see crop option but image rotation feature not available. How can i get.?

Please suggest.

Thanks!
