### ISSUE TITLE
rtmedia_gallery_title is not changing gallery title for shortcode gallery.

### ISSUE THREAD

**Issue by SID177** [rtCamp/rtMedia#1265]
rtmedia_gallery_title is not changing gallery title for the gallery created by [rtmedia_gallery] shortcode. We need a way to change the shortcode gallery title.

**Comment by BhargavBhandari90** [comment]
Not sure but this might be related to https://github.com/rtMediaWP/rtMedia/issues/825

**Comment by Pradeep1308** [comment]
Issue related to #825 and no need add anything separately :+1:
