### ISSUE TITLE
Issues related to ipod and ipad 

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1300]
IPOD:

Videos uploaded fro ipod uploads fine but need to refresh the page to play it otherwise it will display "Download file" text instead of video.

IPAD:

Not able to upload videos from ipad.

Please check this screenshot. 

![dashboard](https://user-images.githubusercontent.com/15173772/54020289-69b60a00-41b3-11e9-8cfc-d7f51e169cdc.png)

**Comment by Pradeep1308** [comment]
https://user-images.githubusercontent.com/61630284/142415337-3bc5aa11-970f-4541-9a09-27872c874cbc.mp4

Working fine with ipad.
