### ISSUE TITLE
[Customer Query] Add the hook that allow the media to be set as featured image for the page

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1342]
As per the requirement, what the customer wants that the media should be set as the `Featured image` when it is uploaded using the uploader shortcode.

E.g. If I have uploaded one image, it will become the featured media for that page/post. After some time, if I upload another image then that latest image would be the featured media for that page/post.

`2522333`

**Comment by Pradeep1308** [comment]
We currently don't provide any such functionality in which the uploaded image is set as the featured image of post/page, It's a whole new functionality to develop. It will require a lot of time and effort for such functionality @thebengalboy should we proceed or not.

**Comment by thebengalboy** [comment]
@Pradeep1308 Yes, I also think the same. Just adding a hook won't help unless you have the functionality to set an image as a featured image. I do not think it will put much value at this moment as we have a lot of other important things to consider now for the user's betterment.

@pooja-muchandikar Would love to hear your thoughts on this. I think we can consider closing this issue and if we get a similar request in the future, we can reopen it.

**Comment by pooja-muchandikar** [comment]
Hi @Pradeep1308 @thebengalboy,

Yes, I have cross checked the query and yes it will be complete new feature which one of the customer had requested. 

If to develop this feature its going to take lot of time and effort then we can hold on this feature request. 

We will close this issue for now and revisit later if any such request comes in urgency.

**Comment by thebengalboy** [comment]
Thanks for the confirmation @pooja-muchandikar; Closing this issue for now and will revisit it later if a similar request comes in.
