### ISSUE TITLE
Fix player button UI issue while posting video/audio as a comment in lightbox

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1351]
The player controller are not aligned properly when the media (audio/video) is posted as a comment in a lightbox.

Please refer to this snapshot. 

1. Video

![Unnamed image (2)](https://user-images.githubusercontent.com/15173772/58706639-470d4900-83d0-11e9-8957-d3ac83a58450.png)

-----

2. Audio

![Unnamed image (3)](https://user-images.githubusercontent.com/15173772/58706706-702dd980-83d0-11e9-9d55-41f2bd57db8b.png)

**Comment by Pradeep1308** [comment]
![Screenshot from 2021-10-06 17-46-46](https://user-images.githubusercontent.com/61630284/136200437-39d811ed-f0bd-453c-b9ef-d325d4d92606.png)

This issue is resolved,
I am closing it.
