### ISSUE TITLE
Please make the user experience more intuitive when user uploads media file bigger than the max file size allowed

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1386]
As per the current implementation, we just inform the user that the `Max File Size Limit: 8M`. 

**1. Testcase 1: When the user performs upload from (group)/activity page** 

The user has added some text and uploaded the bigger file and clicking upon the `Post Update` button, it will simply ignore the media file and just posts the activity update for added text.

Please check this below visual - https://drive.google.com/file/d/10ycjHJOn_Ad9tC9Ie-LkVJ22DN271KIg/view

Please make it more intuitive. 

`Suggestion:`  We can let the user by showing the alert message that file size is not allowed or we can show the current message as it is.

**2. Testcase 2: When the user performs upload from (group)/activity media or using the shortcode** 

That time the user is not allowed to upload the file but still, there should be the alert message.

-----

```
Test Environment

BP V4.3.0
rtMedia V4.5.7
WP V5.2.2

```

**Comment by Pradeep1308** [comment]
PR Merged #1779  , hence closing it here.
