### ISSUE TITLE
function($) wrapper missing on some functions within rtmedia.backbone.js

### ISSUE THREAD

**Issue by colingdi** [rtCamp/rtMedia#1400]
Some code within this file is not suitable for WordPress as it calls the $ function without wrapping as you have in other sections for compatibility mode. Leads to jQuery errors on some builds within comment reply attach media operations. Some parts of the same functions have it correct so not sure how it slipped through.

Line 2417                             $(this).blur();

Line 2607                            $('.rtmedia-comment-media-submit-'+widget_id).focus();

Line 2718                             $( '#' + file.id + ' .plupload_file_status' ).html( progressBar );

**Comment by vishalkakadiya** [comment]
@colingdi Thank you for raising this!

I have QA everything and not facing any issues there, can you provide more details or screenshots here so I can debug specifically on that direction. Thank you!

**Comment by shapaaa** [comment]
This issue is not producible as the code is working fine
```
Test Environment
WordPress Version: 5.8.1
rtMedia Version 4.6.8
```
