### ISSUE TITLE
[Customer Query] Provide media attachment for all levels in activity comment reply

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1425]
Please refer to this ticket - https://wordpress.org/support/topic/how-to-upload-media-in-comment-to-all-level/

-----

Please identify the complexity of adding this feature. This is something where the customer is looking for nesting comments. 

Please document the findings and update me if we should go ahead with this.

**Comment by kjnanda** [comment]
This had been in AC To-Do list

**Comment by knytl** [comment]
Hi, any update on this feature? Would be nice to have it or at least some workaround. Thanks

**Comment by pooja-muchandikar** [comment]
Hi @knytl,

Sorry for the delay in response. 

I will escalate this issue and get this checked by our team and share an update soon. 

Regards,
Pooja

**Comment by pooja-muchandikar** [comment]
Cross-checked this issue with `develop` branch and the fix looks fine.

**Comment by pooja-muchandikar** [comment]
Cross-checked the issue with `master` branch and works as expected.

**Comment by pooja-muchandikar** [comment]
Issue fixed and released in version `4.6.7`

**Comment by pooja-muchandikar** [comment]
Hi @knytl,

We have fixed the issue and

**Comment by pooja-muchandikar** [comment]
Hi @knytl,

> https://github.com/rtCamp/rtMedia/issues/1425#issuecomment-869537938

We have fixed this issue and released in version `4.6.7`. Please update the plugin to latest version. 

Regards,
Pooja
