### ISSUE TITLE
Remove cubepoints info from read me file

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1452]
Since we have dropped the support for this add-on, it should get removed from read me as well.

![rtMediaWP_rtMedia__rtMedia__formerly_Buddypress_Media__adds_advanced_multimedia_functionality_to_WordPress__BuddyPress_and_bbPress](https://user-images.githubusercontent.com/15173772/68674275-8f35b780-057b-11ea-9ff8-5a010ee59298.png)

**Comment by pooja-muchandikar** [comment]
https://github.com/rtCamp/rtMedia/pull/1454#issuecomment-925621254

**Comment by Pradeep1308** [comment]
PR Merged #1454  , hence closing it here.
