### ISSUE TITLE
[Admin Notice] These are the notices which still have dismiss text and it should get changed to dismiss button (x)

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1478]
This issue is partially fixed. Need to work for pending notices where the class(.notice-dismiss) is not getting applied. 

Please check the below screenshot where you can observe that `X` is not applied here.

![Licenses_‹_krupa-rtmedia-plugins_dev2_rt_gw_—_WordPress](https://user-images.githubusercontent.com/15173772/69322080-38f70180-0c6a-11ea-96e1-54faf1508edb.png)

Work done in this PR - https://github.com/rtMediaWP/rtMedia/pull/1177

-----------

Please refer to this snapshot where you can find the relevant information for the same.

![dismis](https://user-images.githubusercontent.com/15173772/69322565-16b1b380-0c6b-11ea-8789-103578120cb4.png)

**Comment by thebengalboy** [comment]
This problem has already solved with this #[PR](https://github.com/rtCamp/rtMedia/pull/1780)

**Comment by pavanpatil1** [comment]
Released with `v4.6.9`
