### ISSUE TITLE
[Customer Query] Masonry in groups activity not working as  expected.

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1489]
This is the response from the customer we received. Please go through it and let me know if any help is needed. 

Also, I have attached the visual. Please check it.

---------

Masonry view no longer works for me.

Previously I was running Version 4.5.4 because this worked and upgrades beyond 4.5.5 broke Masonry view (4.5.5 itself had other issues so I dropped back to 4.5.4). I’d really like to get this resolved so I can upgrade future releases.
Summary:
4.5.4: Masonry view works fine in Buddypress groups
4.5.6 and onwards: It doesn’t. Images appear large in a single column in the activity feed (but still cropped, even without size settings set).

------

https://drive.google.com/file/d/1lla6FOR0jfl-WBkhdsi4PVpK3-inSa4M/view

**Comment by vaishaliagola27** [comment]
@pooja-muchandikar 

I've checked this issue.
The reason why Masonry is not showing properly is that the medium thumbnail size is larger than the section where images are showing.

To resolve this kind of issue, Users have to change Photo Medium size width under `Media Sizes` Setting.

<img width="979" alt="Screenshot 2020-09-16 at 1 53 43 PM" src="https://user-images.githubusercontent.com/11362577/93311774-0be09480-f824-11ea-9889-10e4b22fa9aa.png">

**Comment by pooja-muchandikar** [comment]
@vaishaliagola27 

Checked the issue as per the [comment](https://github.com/rtCamp/rtMedia/issues/1489#issuecomment-693255883) and found that the images are looking bigger because of the media size set in the backend. 

Hence this issue is Invalid as the masonry view depends on the media size set from the backend. Closing this issue.
