### ISSUE TITLE
Add Custom Privacy to the Shortcode

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1542]
Usecase:  To build a gallery that shows the non-logged in users. To have only one query, with which we can display public and member media depending on whether the users are logged in or not.

With the shortcodes we can set a "privacy option" parameter. So we would have to build in two queries that display the images separately and issue more than one error message if only private media are available.

To achieve this we need to find a way to add custom privacy or use multiple privacy.

**Comment by umeshnevase** [comment]
@pooja-muchandikar 
I've added shortcode parameter and also checked thread, but need the confirmation about the privacy option.

**Comment by Pradeep1308** [comment]
I went through the issue and tried to figure out a possible solution but as rtMedia allows single privacy option to be set while uploading a post so it is not possible to add multiple privacy options in our shortcode.
Use case defined by the user in the issue  is not valid as  if a user is not logged in he wont be able to see any post which is not set to public also if global attribute is set to true then privacy parameter will be overridden by default as mentioned in documentation.
