### ISSUE TITLE
Incorrect usage of wp_localize_script() in rtMedia-core

### ISSUE THREAD

**Issue by vermadarsh** [rtCamp/rtMedia#1554]
Hi,

There is an incorrect usage of wp_localize_script() function for rtMedia-core file. The 3rd parameter requires to be an array, wherein string is provided.
There are also multiple instances for the variable localization. All the variables should be bind into an array.

File: /buddypress-media/app/main/RTMedia.php:1108

Reference: https://developer.wordpress.org/reference/functions/wp_localize_script/

Screenshot: https://prnt.sc/qzyi7b

**Comment by Pradeep1308** [comment]
@pooja-muchandikar this issue has been resolved :smile:
Should i close it?

**Comment by pooja-muchandikar** [comment]
@Pradeep1308 

With rtMedia stable version as well this issue is not appearing right?

**Comment by Pradeep1308** [comment]
> @Pradeep1308
> 
> With rtMedia stable version as well this issue is not appearing right?

Yess

**Comment by pooja-muchandikar** [comment]
Alright.

Closing this issue for now.
