### ISSUE TITLE
Unable to upload media to comment if Activity Stream option is disabled 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1563]
```
Test Environment
WordPress: v5.3.2
rtMedia: v4.6.0 and v4.5.2
BuddyPress: v5.1.2 and v4.4.0
```

**Steps to Reproduce**
1. Go to BuddyPress Settings and disabled `Activity stream` option
2. Go to media page and open media in lightbox and try to upload media to comment, media gets uploaded but isn't visible. The media gets stored in media library but isn't visible in the comments.
3. Go back to BuddyPress settings and enabled `Activity stream` option and try uploading media to comment and it works. 

Fatal error is shown
```
Fatal error: Uncaught Error: Call to undefined function bp_activity_filter_kses() in /var/www/htdocs/wp-content/plugins/buddypress-media/app/main/controllers/activity/RTMediaActivity.php:33 Stack trace: #0 /var/www/htdocs/wp-content/plugins/buddypress-media/app/main/controllers/template/RTMediaTemplate.php(704): RTMediaActivity->__construct(Array, 0, '') #1 /var/www/htdocs/wp-content/plugins/buddypress-media/app/main/controllers/template/RTMediaTemplate.php(95): RTMediaTemplate->check_return_comments() #2 /var/www/htdocs/wp-content/plugins/buddypress-media/app/main/routers/RTMediaRouter.php(143): RTMediaTemplate->set_template('/var/www/htdocs...') #3 /var/www/htdocs/wp-includes/class-wp-hook.php(287): RTMediaRouter->template_include('/var/www/htdocs...') #4 /var/www/htdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters('/var/www/htdocs...', Array) #5 /var/www/htdocs/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/var/www/htdocs...') #6 /var/www/htdocs/wp-blog-header.php(19): require_once(' in /var/www/htdocs/wp-content/plugins/buddypress-media/app/main/controllers/activity/RTMediaActivity.php on line 33
```
Reference: https://drive.google.com/file/d/17qyJz4jXbXgNw_2IRE5eHfnvAssg2JpS/view

Queries: 
- Does media uploads on comments depends on activity stream?
- If this is disabled should we hide the upload button?

**Comment by SID177** [comment]
We can use `wp_kses_post` or similar function as alternative to `bp_activity_filter_kses`. But it'll still try to create activity, which should be avoided.
Also in comment, the image is not displayed properly when the above point is addressed, I think this can be handled by further debugging and it shouldn't be very hard to do.

**Comment by kjnanda** [comment]
@SID177 Thank you for taking the time to address the query.

Much appreciated! 🙏 

Thanks
