### ISSUE TITLE
UI issues with video files in Mobile device

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1566]
If in media size settings video size is set to 960 x 540px then the UI gets distorted in mobile device.

When viewing the Activity Stream on a mobile device, the 540px height remains and bars appear above and below the video as show in the screenshot.

![Activity_–_krupa_–_test](https://user-images.githubusercontent.com/41000648/75765401-78eb7b80-5d65-11ea-9709-bf7553cb4f48.png)

**Comment by dishitpala** [comment]
@pooja-muchandikar Please can you share more details because i am not able to replicate the issue

which theme you are using
and we have 2 different settings for video in which we have to add the height and width

![Screenshot 2020-07-22 at 8 05 20 PM](https://user-images.githubusercontent.com/25063903/88189584-d6ba2a80-cc56-11ea-881b-8215c301959f.png)

**Comment by pooja-muchandikar** [comment]
@dishitpala 

Theme 2019 

You can set the height and width for activity player and check in mobile device this issue is specifically for mobile device.

**Comment by shapaaa** [comment]
@pooja-muchandikar I am not able to reproduce this issue.I tried to do it with 2021 theme but no spacing has been shown as mentioned above.

**Comment by pooja-muchandikar** [comment]
@shapaaa 

Did you try with 2019 theme in mobile device? Let me know if its working fine with 2019 theme. 

Try with both BuddyPress Legacy Template option and Nouveau template option.

**Comment by shapaaa** [comment]
Can't see issue here as mentioned above
![image](https://user-images.githubusercontent.com/48183855/140893868-1f00657e-6ff6-4b3e-bb29-084f25731b6b.png)

**Comment by shapaaa** [comment]
This issue is resolved and working fine.
The video size is correct & there is no space. 
```
Test Environment
WordPress Version: 5.8.1
rtMedia Version 4.6.8
```
![image](https://user-images.githubusercontent.com/48183855/140894239-295f4a78-20a8-4a74-b32f-00a7b5c3448e.png)
