### ISSUE TITLE
Allow the subscriber to Modify Image functionality 

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1645]
![Media_–_Krupa_Nanda_–_krupa_dev5_rt_gw](https://user-images.githubusercontent.com/15173772/80940079-380ef200-8dfc-11ea-9630-438a79432dbd.png)

**Comment by shapaaa** [comment]
After discussion with Mehedi,Pradeep & Sabbir there is some security concerns by giving this permission to subscriber & there is no use case of subscriber role as all roles will get edit_post capability.
