### ISSUE TITLE
Issue with WP_Offload_Media when using S3 signed URL

### ISSUE THREAD

**Issue by ExoGeek** [rtCamp/rtMedia#1656]
I use wp_offload_media to offload medias to S3. Recently, I've enabled the signed URL feature (on Amazon S3). Everything goes well on the wordpress side (In the dashboard, I can see media image in WP Media library of wordpress). 

But when I visit the website (Profile -> Media), the image is not shown.

The reason is because the **URL of the media is not signed** (it links to S3 but not the signed URL).

**Comment by ExoGeek** [comment]
Hello,

I've found the problem : see line 751 in the file rtmedia-function.php

`$src = apply_filters( 'rtmedia_media_thumb', $src, $media_object->id, $media_object->media_type );

// Added timestamp because conflict with cache image.
$src = $src . '?' . time();`

Maybe that you should invert the code like that : 

`// Added timestamp because conflict with cache image.
$src = $src . '?' . time();

$src = apply_filters( 'rtmedia_media_thumb', $src, $media_object->id, $media_object->media_type );`

Regards,

**Comment by ExoGeek** [comment]
I've found one other place where you add "?time()" at the end of the src image (lightbox). This break Signed URL.

File : rtmedia-functions.php
Line : 591
`$html = "<img src='" . set_url_scheme( $src[0] . '?' . time() ) . "' alt='" . esc_attr( $rtmedia_media->post_name ) . "' />";`

**Comment by pooja-muchandikar** [comment]
Hi @ExoGeek 

We will look into this issue and get back to you. 

Thanks and Regards,
Pooja

**Comment by SID177** [comment]
Hi @ExoGeek 

I think S3 Pre-Signed URLs have query string appended, and we're adding `?` directly to the URL, which could be breaking the image.

Can you please confirm by providing image URL of any broken image. You might need to inspect element and check from browser. Or you can provide us access to 1 of your page where the images are broken.

Thanks

**Comment by ExoGeek** [comment]
Hi @SID177 

You're right. rtmedia adds "?1592838041" ('?' . time();) at the end of the src image attributes.

For privacy reason, these images are not accessible publicly but you will understand the pattern.

Well formated URL : https://**MyS3BucketName**.s3.eu-west-3.amazonaws.com/localhost/2020/06/22155525/3f083c89-a5c7-492c-938d-467d2d666dc5-1080x675.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AZIA46ZC73DSWOHCZ53N%2F20200622%2Feu-west-3%2Fs3%2Faws4_request&X-Amz-Date=20200622T145545Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Signature=fd92ec9003d6c72983145132cbab7df7506dec923111b2a482e045fb724140773

RTMedia : https://**MyS3BucketName**.s3.eu-west-3.amazonaws.com/localhost/2020/06/22155525/3f083c89-a5c7-492c-938d-467d2d666dc5-1080x675.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AZIA46ZC73DSWOHCZ53N%2F20200622%2Feu-west-3%2Fs3%2Faws4_request&X-Amz-Date=20200622T145545Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Signature=fd92ec9003d6c72983145132cbab7df7506dec923111b2a482e045fb724140773?1592838041 

**?1592838041** is added. This break the URL.

**Comment by pooja-muchandikar** [comment]
Hi @ExoGeek,

We have fixed this issue and released with version `v4.6.4`. Please update the plugin with the latest version. 

Regards,
Pooja
