### ISSUE TITLE
Add attachment_ids (post_id) to the hook rtmedia_after_add_media

### ISSUE THREAD

**Issue by ExoGeek** [rtCamp/rtMedia#1657]
Hello,

It would be usefull for developers to get wordpress attachment id when media is uploaded via rt_media (I mean : wp_posts.id).

I've hooked "rtmedia_after_add_media" but $media_ids only contains rt_media.id.

If we need to have the attachment_id, we need to make a new query. But in the function "add" (in the file RTMediaMedia.php), we already have $attachment_ids containing that information.

Maybe you could all this variable to 

`do_action( 'rtmedia_after_add_media', $media_ids, $file_object, $uploaded,  $attachment_ids);`

Regards

**Comment by SID177** [comment]
Hi @ExoGeek 

You can use rtMedia's built in function `rtmedia_media_id` instead of writing a query. It'll give you attachment ID of any rtMedia ID.

However we will be adding `attachment_ids` in the action to save extra query.

**Comment by pooja-muchandikar** [comment]
Hi @ExoGeek,

We have fixed this issue and released with version `v4.6.4`. Please update the plugin with the latest version. 

Regards,
Pooja
