### ISSUE TITLE
Create a hook to modify the default global album name "Wall Posts" (add_filter)

### ISSUE THREAD

**Issue by ExoGeek** [rtCamp/rtMedia#1665]
Hello,

It would be nice to be able to modify the name of the default album via add_filter hook. 

Maybe something like that :

```
$global_album_name = apply_filters( 'rtmedia_global_album_name_string', esc_html__( 'Wall Posts', 'buddypress-media' ) );
$global_album = $album->add_global(  $global_album_name  );
```

Regards,

**Comment by pooja-muchandikar** [comment]
Hi @ExoGeek,

To change the default global album name you can check out our [rtMedia default Album](https://rtmedia.io/products/rtmedia-default-albums/) plugin. 

You can go the following settings path `rtMedia > Default Album`  and change the name of the global album wall posts to any other name as  required. With this plugin you can create multiple default albums for your site and set one as the global default album for everyone.

Regards,
Pooja
