### ISSUE TITLE
Issue with media displaying in lightbox on activity page

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1672]
```
Test Environment
rtMedia: v4.6.3
BuddyPress: v6.1.0
```

**Steps to Reproduce**
- Go to rtMedia settings > BuddyPress > and set Number of media items to show in activity stream to 5 ( or any other number )
- Now, go to media page and upload media ( more than 5 images )
- Go to activity page and observe that media shown on activity page, the media will be shown as the number defined in the buddypress settings, but the other images are not shown not even in the lightbox
- In specific activity card if images are present in lightbox only those images should be shown instead of all the activities from the activity page

Refer: https://drive.google.com/file/d/1E6WecxnI-ah3Sg76lQenrHLYjFU_b-pC/view

**Comment by Pradeep1308** [comment]
Every Media upload will create activity so  light-box in activity stream shows all media uploaded and as of now functionality works fine.
