### ISSUE TITLE
Hide profile uploads from activity page

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1693]
### Requirement

Option to hide the profile uploads from activity page. Whenever media is uploaded from media tab in the profile, it creates an activity in the activity page. Need an option or a code snippet to hide the profile uploads to be shown on activity page. 

---

### Issue

We have `Allow upload from activity stream` option in BuddyPress tab rtMedia settings. 

This option is available for two different actions
- If enabled upload button in activity page is shown
- Create activities if media is uploaded from profile media page

Because of which the requirement is not full-filled. If we disable this option then profile uploads will not be shown on activity page but also will disable the upload button from activity page.

---

### Suggestions

We need to have separate options for both the actions. We can give following options like

- An option to `Enable/Allow upload from activity stream` option to enable/disable
- An option to `Create activity/notification for profile media uploads` option to enable/disable

 ---

### Notes

If changes done for profile uploads we might need to check for group uploads as well.

**Comment by thebengalboy** [comment]
Hi @pooja-muchandikar 

I have gone through the issue and checked the workflow as well. So, the thing is, it only creates Activity Stream/Side wide activity if you upload media with the `public visibility. But if you make it private, it doesn't create an activitiy.

The workflow seems okay to me. Can you please confirm?

**Comment by pooja-muchandikar** [comment]
Hi @thebengalboy 

Cross-checked on demo site and it does create activity for media uploads with private visibility & other visibility options as well.

**Comment by thebengalboy** [comment]
It's visible to all the users or only for the user who uploaded? @pooja-muchandikar

**Comment by pooja-muchandikar** [comment]
Only private media is visible to user who uploaded and rest media is visible to all users based on the privacy set.

**Comment by thebengalboy** [comment]
What do you think about the workflow then? Should it be updated or it's okay as it is now?

I feel somehow it's okay now.
1. Private media stream can see the author only
2. 'Friends' media stream can see by the friends
3. 'Public' media stream can be seen by everyone

**Comment by pooja-muchandikar** [comment]
My only concern was if as a user(who is uploading media) doesn't want the upload to create activity then how can I hide it?

**Comment by thebengalboy** [comment]
He/she can make it 'Private' in that case. Private media creates a stream for the author only, that's not a problem as long as no one other can see it.

We can certainly have an option in the settings for this but having an extra option just for the private status doesn't create much value on it compared to the effort. It'll work as it is, just will hide the stream from him/her.

Rather, we can try to convince the user that this stream is only for you, not for others.

**Comment by pooja-muchandikar** [comment]
Alright @thebengalboy 

We will keep [this](https://github.com/rtCamp/rtMedia/issues/1693#issuecomment-972751336) workflow for now. 

Then I think we can close this ticket.
