### ISSUE TITLE
Sitewide activity post media is missing on /members/username/media (bp nouveau template)

### ISSUE THREAD

**Issue by razor2016** [rtCamp/rtMedia#1704]
Hi rtCamp,

Thanks for this amazing plugin.

I'm reporting a bug when using rtmedia with bp nouveau template pack.

When a user post media in the sitewide activity, it should appear on his/her profile media tab (example.com/members/username/media). This is the expected behavior and works fine with the bp legacy template.

**The problem**:
The problem only seems to occur with the bp nouveau template, and when the user uploads media from the sitewide activity, not from profile > activity (works fine there).

It's tricky, so I will try my best to explain "why and how to recreate it on your end."

**Scenario-1 (when it works):**
If the user doesn't have `#whats-new-post-in` select-box in his/her sitewide activity uploader and if he/she post a photo/video there, it appears on his/her profile media tab (members/username/media). This is expected.

![Capture](https://user-images.githubusercontent.com/20941700/98223989-180fe500-1f7d-11eb-827b-24de39ba949e.PNG)
![Capture1](https://user-images.githubusercontent.com/20941700/98223993-19411200-1f7d-11eb-93c2-c31fa4ab00b0.PNG)

**Scenario-2 (when it doesn't work):**
Let's say the user has joined a group, so now he/she has `#whats-new-post-in` select-box to select from, when posting a photo or video. Now if the user post a photo in the sitewide activity, that photo doesn't appear in his/her profile (members/username/media).

![Capture2](https://user-images.githubusercontent.com/20941700/98225274-bbadc500-1f7e-11eb-989a-08cd7fc123f4.PNG)
![Capture4](https://user-images.githubusercontent.com/20941700/98225279-bcdef200-1f7e-11eb-9fce-036b39839c87.PNG)

**The cause of the problem**: 
I tried to find the cause of the problem and what I found is:
In Scenario-1, the context_id of the uploaded media has a value 1 (see the `wp_rt_rtm_media` db table).
in Scenario-2, the context_id of the uploaded media has a value 0/null (see the `wp_rt_rtm_media` db table).

I didn't go further, checking why it gets 0/null in the scene-2. I am leaving that too you since everyone will benefit from it.

To recreate the issue:
1. you must use the bp nouveau template pack.
2. The user must have `#whats-new-post-in` select-box in his/her activity uploader. Perhaps join a group so that the `#whats-new-post-in` select-box would appear.
3. user has to post media at the sitewide activity (/activity), not at member/username/activity.

I hope you understand. If you have any question, let me know.

Thanks

**Comment by pooja-muchandikar** [comment]
Hi @razor2016 

Thanks for reporting the issue, we were able to reproduce the issue at our end. 

We will fix it and update you once the fix is released. 

Regards,
Pooja

**Comment by SID177** [comment]
The issue only appears in Nouveau template, because when uploading a media from Nouveau, it sets proper `context`, but the `context_id` is wrong.

In Legacy template, the `context_id` is 0 in upload request parameters, where in Nouveau it's `profile`, which is wrong.

### Nouveau Template request params
![Screenshot 2020-11-05 at 6 41 15 PM](https://user-images.githubusercontent.com/23107546/98245150-801ef500-1f96-11eb-8ebf-2c9d8daf854a.png)


### Legacy Template request params
![Screenshot 2020-11-05 at 6 43 06 PM](https://user-images.githubusercontent.com/23107546/98245322-c07e7300-1f96-11eb-947c-87355eeafd30.png)


The media is uploading to the right album, but `context_id` wrong, which needs to be fixed.

**Comment by pooja-muchandikar** [comment]
@SID177 

Tested with `pre-release` branch and the fix works as expected.

**Comment by pooja-muchandikar** [comment]
@razor2016 

We have fixed this issue and released the fix with version `4.6.5` . Please update the rtMedia plugin to latest version. 

Please let us know if there is anything else that we can help you with.

Regards,
Pooja

**Comment by razor2016** [comment]
@pooja-muchandikar 

Yes, it works, thanks. I think I have found 2/3 more glitches. I will open new issues. I am gonna close this issue now as It seems to be solved.

Thank you so much!
