### ISSUE TITLE
Incorrect support URL in sticky topic on WordPress support forums of rtMedia

### ISSUE THREAD

**Issue by gagan0123** [rtCamp/rtMedia#1722]
On WordPress support forums, a sticky topic was created to ensure that users requesting support would be directed to correct way of asking for support, but the URL listed in there points to a 404 link.
https://rtcamp.com/support/forum/rtmedia
![image](https://user-images.githubusercontent.com/1535505/103524644-e3001000-4ea3-11eb-8d15-cd14a33799ea.png)

Possible resolutions:
1. Get the link corrected in Support forums(would be difficult).
2. Add a redirection from that URL to where we're entertaining support requests (could be issues link of this repo).
3. We can remove "Sticky" from that topic, because as I can see, Pooja is currently offering help on support requests on WordPress support forums.

**Comment by pooja-muchandikar** [comment]
We are currently providing support to customers from following portals https://rtmedia.io/support/ and https://wordpress.org/support/plugin/buddypress-media/active/

@nitun I have removed the `Sticky` option from that support forum. 

cc: @gagan0123

**Comment by pooja-muchandikar** [comment]
Closing this ticket, as necessary changes have been done as requested.
