### ISSUE TITLE
Javascript string translation errors

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1723]
Need to work on following ticket, details are mentioned in the ticket. https://wordpress.org/support/topic/javascript-string-translation-errors/#post-13865199

**Comment by NicestRudeGuy** [comment]
@vaishaliagola27  
Inside **rtMedia plugin** we have used wp_localize_script method several places 
for example https://github.com/rtCamp/rtMedia/blob/develop/app/main/RTMedia.php#L1319
`
wp_localize_script( 'rtmedia-main', 'rtmedia_gallery_reload_on_upload', '1' );
`
but inside the official documentation the last param is supposed to be an array https://developer.wordpress.org/reference/functions/wp_localize_script/

the issue arrises when we the person uses php v8 with WP. currently wordpress 5.6 supports php 7.4 but php 8.0 support is in beta so in near future we will face this issue ( warnings ) . several of our addons might be affected if we change it.

Also for single data do we need to pass array or we can just pass the data directly ?

**Comment by vaishaliagola27** [comment]
@NicestRudeGuy 

We have use single dimensional array as value and change in respective js files.

**Comment by NicestRudeGuy** [comment]
@vaishaliagola27 
These only exist in PHP 8.0 and are everywhere even in the addons will require update in all the addons as well .  Cant seem to find a better way to solve this problem except manually updating rtMedia plugin and all the addons

**Comment by SID177** [comment]
Maybe we can do something like this:
- Make changes in core rtMedia plugin and test it, keep the old code for now so it works with older versions of premium add-ons and themes
- By referring to these changes, make changes in premium add-ons and themes, test it and release them, make sure to add backward compatibility in add-ons and themes so that it works with recent rtMedia versions
- Release rtMedia core with the changes
- After 2-3 releases, maybe we can remove the older code for `wp_localize_script` from core plugin and backward compatibility code from add-ons and themes

**Comment by NicestRudeGuy** [comment]
> Maybe we can do something like this:
> - Make changes in core rtMedia plugin and test it, keep the old code for now so it works with older versions of premium add-ons and themes
> - By referring to these changes, make changes in premium add-ons and themes, test it and release them, make sure to add backward compatibility in add-ons and themes so that it works with recent rtMedia versions
> - Release rtMedia core with the changes
> - After 2-3 releases, maybe we can remove the older code for `wp_localize_script` from core plugin and backward compatibility code from add-ons and themes


Compatibility is not an issue here since the change will only remove warnings not alter any functionality. I found that at few places we aren't getting the error maybe the functions wasn't getting called at the moment but when it will be called the warnings will appear.

**Comment by NicestRudeGuy** [comment]
Fixed it for admin side , now onto the main dir .

**Comment by NicestRudeGuy** [comment]
Im done with the plugin , pushed the code to this branch https://github.com/rtCamp/rtMedia/tree/GH-1723 
we would need to do the same thing will every rtMedia Addon.
