### ISSUE TITLE
How to close the gap in buddypress?

### ISSUE THREAD

**Issue by hectorcchan** [rtCamp/rtMedia#1725]
Hi guys, I am a beginner at wordpress.  There is a problem that the rtmedia plugin doesn't seem to match my website's width. There is a big white blank on the right side.

![rt1](https://user-images.githubusercontent.com/69570451/108629825-b37d8500-749c-11eb-80e5-724da6c3cf8d.png)
This is the normal size of buddypress.

![rt2](https://user-images.githubusercontent.com/69570451/108629826-b5474880-749c-11eb-881c-892e8906245d.png)
The gap would show on the right side when i clicked into rtmedia section.

Please help me to solve this issue, I've spent a lot of time on that. Thank you so much.

**Comment by pooja-muchandikar** [comment]
Hi @hectorcchan,

We have already discussed this issue on our support portal [here](https://wordpress.org/support/topic/ui-doesnt-match-with-buddypress/) and also have answered to your query. 

Closing this ticket as we will continue discussion over the ticket.
