### ISSUE TITLE
Multiple media upload and privacy drop-down are shown

### ISSUE THREAD

**Issue by patelanuj2612** [rtCamp/rtMedia#1735]
https://paste.pics/D6876
This issue still persists, After little investigation found that , if you open multiple tabs in browser, first tab request all activity using ajax and remaining two tabs retrieve content using cache or something, so no ajax request sent for remaining two tabs. And code that resolve this issue written in ajaxComplete part of code. Since two tabs had no ajax request , ajaxcomplete will not called and it gives this type of output. See below reference code 

```
jQuery(document).ajaxComplete(function(event, xhr, settings) {
    if ('legacy' !== bp_template_pack && bp_template_pack) {
        var get_action = get_parameter('action', settings.data);
        if (('activity_filter' === get_action || 'post_update' === get_action || 'get_single_activity_content' === get_action || 'activity_get_older_updates' === get_action) && 'undefined' !== typeof rtmedia_masonry_layout && 'true' === rtmedia_masonry_layout && 'undefined' !== typeof rtmedia_masonry_layout_activity && 'true' === rtmedia_masonry_layout_activity) {
            setTimeout(function() {
                apply_rtMagnificPopup('.rtmedia-list-media.rtm-gallery-list, .rtmedia-activity-container ul.rtmedia-list, #bp-media-list,.bp-media-sc-list, li.media.album_updated ul,ul.bp-media-list-media, li.activity-item div.activity-content div.activity-inner div.bp_media_content, .rtm-bbp-container, ul.rtm-comment-container');
                rtmedia_activity_masonry();
                rtmedia_activity_stream_comment_media();
            }, 1000);
        } else if (('activity_filter' === get_action || 'post_update' === get_action || 'get_single_activity_content' === get_action || 'activity_get_older_updates' === get_action)) {
            setTimeout(function() {
                apply_rtMagnificPopup('.rtmedia-list-media.rtm-gallery-list, .rtmedia-activity-container ul.rtmedia-list, #bp-media-list,.bp-media-sc-list, li.media.album_updated ul,ul.bp-media-list-media, li.activity-item div.activity-content div.activity-inner div.bp_media_content, .rtm-bbp-container, ul.rtm-comment-container');
                rtmedia_activity_stream_comment_media();
            }, 1000);
        }
    }
});
```

Please help me on this. Thanks

_Originally posted by @patelanuj2612 in https://github.com/rtCamp/rtMedia/issues/1294#issuecomment-878260645_

**Comment by pooja-muchandikar** [comment]
Hi @patelanuj2612,

Sorry for the inconvenience you are facing at your end. 

We will debug this issue further and get back to you soon. 

Thanks,
Pooja

**Comment by pooja-muchandikar** [comment]
Hi @patelanuj2612,

We tried to reproduce the issue but we are unable to replicate it. We tried reproducing the issue by the method shared by you but still we were unable to replicate. 

Can you please share which version of WordPress, BuddyPress and rtMedia is currently active on your site?

Regards,
Pooja

**Comment by patelanuj2612** [comment]
WordPress - 5.6.4
BuddyPress - 1.5.6
rtMedia - 4.6.6

**Comment by pooja-muchandikar** [comment]
Thank you for the details. 

We will check and get back to you.

**Comment by pooja-muchandikar** [comment]
Hi @patelanuj2612,

We tried to replicate the issue on the test environment you shared and facing conflicts as the version of WordPress and BuddyPress you are using are very older versions. 

Till date so many things have changed in BuddyPress plugin (current version: 9.0.0) and WP itself because of which the issue you are facing may be conflicting with the older version.

You can try updating WordPress and BuddyPress to its latest version and check if you are still facing the same issue. 

**IMPORTANT NOTE: Please update the WordPress and BuddyPress plugin's on your local or staging site first. Do not perform this action directly on Production site it is not recommended.** 

Let us know if this helps. 

Regards,
Pooja

**Comment by patelanuj2612** [comment]
Hi @pooja-muchandikar 

Thank you for your valuable feedback. Issue is resolved by updating WordPress and BuddyPress plugin.
