### ISSUE TITLE
after uploading audio and video files are not working.

### ISSUE THREAD

**Issue by alijawadbutt4300** [rtCamp/rtMedia#1737]
I am not ale to see anything after uploading media files through rtmedia

**Comment by pooja-muchandikar** [comment]
Hi @alijawadbutt4300,

Sorry to hear the inconvenience you are facing at your end.

Can you please confirm if you are facing the same issue with the WordPress default theme with only BuddyPress and rtMedia enabled? 

You can also go through this troubleshooting guide as well - https://rtmedia.io/docs/troubleshooting/basic-diagnosis-guide/

If possible please share the visual of the issue you are facing. 

Regards,
Pooja

**Comment by Pradeep1308** [comment]
![Screenshot from 2021-10-08 11-44-47](https://user-images.githubusercontent.com/61630284/136507616-8733cf34-28ce-4ab3-868b-3a3b29c6a4f6.png)
Media is visible and rtMedia Working fine
