### ISSUE TITLE
Issue with uploading of Unsupported media

### ISSUE THREAD

**Issue by ank1traj** [rtCamp/rtMedia#1738]
### Environment
**OS** - Windows
**Browser** - Chrome
**Architecture** - x64
**WordPress Version** - 5.8
**Tested with Single site**

| name  | About  | labels  | assignees|
|---|---|---|---|
|  🐛 Bug Report |  Blank activity after unsupported media get upload🤔. | bug  |   |

**Description** - rtMedia plugin support .jpg, .jpeg, .png, .gif extensions of Image, .mp4 for video and .mp3 for audio. After adding media with unsupported format and after uploading it create a blank activity in the activity stream.

**Expected** - After upload, it should not create a blank activity in the activity stream.

**Actual** - After upload, it's creating a blank activity in the activity stream.

![image](https://user-images.githubusercontent.com/32160084/131811364-512cc3aa-d3b5-42ac-b184-256e053dfcbf.png)

**Steps to reproduce issue** - 

**NOTE- User must be logged**

1. Click on the post form
2. Click on the upload icon to upload media
3. Upload unsupported format media
4. Click on upload post

**Acceptance criteria** - It should not create any blank activity.

**Comment by pooja-muchandikar** [comment]
https://github.com/rtCamp/rtMedia/pull/1741#issuecomment-919888121

**Comment by ank1traj** [comment]
Closing this issue, as necessary changes have been done as requested.

**Comment by pooja-muchandikar** [comment]
Cross-checked this issue with `develop` branch and the fix looks fine.

**Comment by pooja-muchandikar** [comment]
Cross-checked the issue with `master` branch and works as expected.

**Comment by pooja-muchandikar** [comment]
Issue fixed and released in version `4.6.7`
