### ISSUE TITLE
Broken theme demo URL

### ISSUE THREAD

**Issue by thebengalboy** [rtCamp/rtMedia#1740]
**Environment**
OS - MacOSX
Browser - Chrome: Version 92.0.4515.159
WordPress Version - 5.8.1

**Description**: In the rtMedia plugin, the theme 'Live Demo' URL needs to be updated as it redirects to a wrong/old URL.
**Problem**: When you click on the 'Live Demo' button, it's taking to a broken URL.
**Expected**: It should take to the correct demo URL.

**Steps to reproduce**:
- Please navigate to wp-admin→rtMedia→themes
- Hover over any theme and click on the 'Live Demo' option
- You'll be taken to a wrong/old URL that is broken.

**What should be the correct demo URL?**
- InspireBook→ https://inspirebook.demo.rtmedia.io/
- rtDating→ https://rtdating.demo.rtmedia.io/
- FoodMania→ https://foodmania.demo.rtmedia.io/

**Reference Screenshot**
<img width="1429" alt="Screenshot 2021-09-14 at 5 00 52 PM" src="https://user-images.githubusercontent.com/5962216/133246155-22257c8f-9a94-437c-94a7-151c8d41c739.png">

**Comment by pooja-muchandikar** [comment]
https://github.com/rtCamp/rtMedia/pull/1742#issuecomment-919824914

**Comment by pooja-muchandikar** [comment]
Cross-checked this issue with `develop` branch and the fix looks fine.

**Comment by pooja-muchandikar** [comment]
Cross-checked the issue with `master` branch and works as expected.

**Comment by pooja-muchandikar** [comment]
Issue fixed and released in version `4.6.7`
