### ISSUE TITLE
activity - edit post

### ISSUE THREAD

**Issue by enry08** [rtCamp/rtMedia#1754]
Dear **STAFF** good evening,

I'm here to talk to you again because some members registered to date have raised some criticisms for the absence of that "EDIT" button post in the "activity" area. 
I am aware of your difficulties but I ask you could you share this problem with the community to find a solution?

Is it possible that with the next updates the problem will be overcome? 
Maybe there is the possibility to insert the "edit" button as a link that leads to another resource that allows you to edit the post?
I uploaded a medello for WordPress and in the activity page of this social network it is not possible to modify the published post.
I attach screenshots adn web site
![screenshot-1](https://user-images.githubusercontent.com/92148293/136517841-f2b413e7-e645-4782-916a-3f40a83df866.png)
![screenshot-2](https://user-images.githubusercontent.com/92148293/136517889-6e2eb240-da7e-469f-ac26-33790f307f6e.png)

https://frenz17.com/activity/ - enrico@sinetweb.net 
I apologize for my important request

Waiting for your reply, I cordially greet you.

**Comment by thebengalboy** [comment]
We'll look into this soon @enry08 

Related #1712

**Comment by Pradeep1308** [comment]
issue mentioned here already [issue](https://github.com/rtCamp/rtMedia/issues/1712l), hence closing here.
