### ISSUE TITLE
After uploading media, &nbsp; added to text-area - Activity Page

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#1756]
On the Activity page, when we upload a media, &nbsp; added in textarea and due to that user is not able to tap inside the text area.

**Steps to Reproduce:**

1. Go to Activity -> upload a media using the media uploader.
2. then click on the text area. (What's new section)

Expected Result:  Remove this` &nbsp; `(non-breaking space)

https://user-images.githubusercontent.com/44057535/136782931-38287614-c6c1-42ba-9b7e-99044af76386.mp4

**Comment by Pradeep1308** [comment]
BP doesn't support media so there is condition that text field can't be empty, that's why we have added &nbsp so that we can simply upload media by our rtMedia plugin.
So this issue is not valid anymore. :+1:
