### ISSUE TITLE
Issue observed on Pre-release Branch

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#1793]
**Test Environment Used**
```
 WordPress: v5.9 Beta. 
 BuddyPress: 9.1.1
 rtMedia - Pre-release branch
```

- [x] Default album is not displayed on group after uploading image in group media

**Describe the bug**
In a group, after uploading media the count for the album is displayed but `Sorry !! There's no media found for the request !!` message is displayed instead of an album. The issue is observed on a `pre-release` branch. 

Create a group and in media, upload the media with 

**Expected behavior**
The album should be displayed. 

**Screenshots or Visual**

https://user-images.githubusercontent.com/44057535/145826741-d5b7271d-d638-4146-877b-ff7029ac8cf5.mp4

---

- [x] Lightbox type interface is opened on album page. 

On the album page, after uploading the media lightbox type interface is opened. 

Steps to reproduce: 
1. Go to profile and In media, click on the album. 
2. Upload the media and open the album. 
3. Observe the UI. 

https://user-images.githubusercontent.com/44057535/145844751-a8d8ab8b-52bb-47c3-87b6-2b5d5b76803f.mp4

---

- [x]  Selected color button UI is not displayed properly in watermark addon settings. 

Addon - rtMedia Photo Watermark

Steps to reproduce: 
Install the rtMedia watermark addon and in settings in the watermark section, select the color. 

![image](https://user-images.githubusercontent.com/44057535/145939572-faf32e37-1640-4166-96d3-71e8f5146122.png)

---

- [x] Play,pause button not visible in playlist. 

Addon: rtMedia Playlists

After adding music to the playlist, the play pause button is not visible for the audio. 

Steps to reproduce: 
Install the rtMedia playlist addon, It will add one menu(Playlist) in media. Click on the playlist and create a playlist. Add the music to the playlist and observe the UI. 

Note: Maybe the issue is related to the addon. but as I check this button coming from the plugin. Can you check if this is related to plugin or addon? If related to addon then we can move this to the addon. 

![image](https://user-images.githubusercontent.com/44057535/145959942-7d9c6cd1-e89b-4dd3-9639-c2bd398ceb0e.png)

**Comment by Pradeep1308** [comment]
@pavanpatil1 issue is resolved , check it. :+1:
