### ISSUE TITLE
Activity Masonry layout doesn't work in the newest version

### ISSUE THREAD

**Issue by divineproclamation** [rtCamp/rtMedia#1804]
Hi,

The "Activity Masonry" option doesn't work with the newest rtmedia version (4.6.9). It doesn't add the "masonry" class to the activity list (`.rtmedia-list`). See the screenshots below.

RTMedia Settings: 
![rtmedia-settings--masonry-1](https://user-images.githubusercontent.com/97110057/148078857-e33d5c26-029f-41c0-ad4c-de2371257102.PNG)
![rtmedia-settings--masonry-2](https://user-images.githubusercontent.com/97110057/148078865-66221691-27d3-4a05-a6b3-8f919f271bf8.PNG)

Frontend Output:
![rtmedia--frontend-masonry-1](https://user-images.githubusercontent.com/97110057/148079100-7118db0c-1cb1-41de-9d91-6667657c4d43.PNG)
![rtmedia--frontend-masonry-2](https://user-images.githubusercontent.com/97110057/148104017-c9eb1259-0139-4f97-a101-b22440caf6e4.PNG)

Try testing it. You will see.

Thanks

**Comment by thebengalboy** [comment]
Hi @divineproclamation 

After enabling the masonry view, did you regenerate the thumbnail for the masonry view? Like it advised here: https://prnt.sc/263f9c5

We'll also check it soon and get back to you..

**Comment by divineproclamation** [comment]
Yes, I did. Please try it on your side. The `.masonry` class is missing in the `.rtmedia-list` container as you can see in the 3rd screenshot I attached in the issue above. Thanks

**Comment by thebengalboy** [comment]
Hi @divineproclamation 

We solved the issue with this PR#1808 

Thank you for being with us.
