### ISSUE TITLE
Upload photos and post

### ISSUE THREAD

**Issue by Gayanlife** [rtCamp/rtMedia#1805]
Can't upload photos or post on Bbpress activities page.
Please correct it if not can't do uploads anything

**Comment by thebengalboy** [comment]
Hello @Gayanlife 

It comes with a premium add-on. Please check this: https://rtmedia.io/products/rtmedia-bbpress-attachments/

If you have a further query on this, please feel free to reach us through our [support channel](https://rtmedia.io/support/).

Thanks
