### ISSUE TITLE
Showing a console error in rtmedia admin page.

### ISSUE THREAD

**Issue by sabbir1991** [rtCamp/rtMedia#1810]
**Describe the bug**
In rtmedia admin page when we open the console we will get `uncaught SyntaxError: Unexpected token ';'`

**To Reproduce**
1. Open console in chrome
2. Go to 'rtMedia' plugin page.
3. See error in consoel

**Expected behavior**
There should be no console error in rtmedia page.

**Screenshots or Visual**
<img width="1439" alt="Screenshot 2022-01-10 at 10 48 05 PM" src="https://user-images.githubusercontent.com/2692939/148804725-c77d8796-9ac0-44e1-bec2-7ed922e1f997.png">

**Test Environment Used**
 - WordPress: [e.g V5.8.3]
 - BuddyPress: [e.g. V9.2.0]
 - rtMedia [e.g. V4.6.9]
 - Browser [e.g. chorme]

**Comment by thebengalboy** [comment]
@pavanpatil1 As the PR got merged already, please could you verify this once and close the issue if already solved?
