### ISSUE TITLE
Update notice of Pro addons shows incorrectly - should be removed

### ISSUE THREAD

**Issue by kamalahmed** [rtCamp/rtMedia#1816]
**Describe the bug**
Update notice of Pro addons shows incorrectly - should be removed from this plugin and it should show from the pro version only.

**To Reproduce**
1. Install this plugin and 'rtmedia pro'
4. See error in the header

**Expected behavior**
Remove the notice from the free version. 

**Screenshots or Visual**
[If applicable, add screenshots or visual to help explain your problem.](https://user-images.githubusercontent.com/44057535/150294766-36939427-27bd-41a2-8d05-6b2c9af6b520.png)

**Test Environment Used**
 - WordPress: [V5.9]
 - BuddyPress: [V10.0.0]
 - rtMedia [V4.6.9]
 - Browser [Chrome on mac os 12.1]

**Comment by thebengalboy** [comment]
@pavanpatil1 Please could you verify the PR against this issue?

**Comment by pavanpatil1** [comment]
Fixed in #1819. Hence closing this issue.
