### ISSUE TITLE
Album for non-admin user

### ISSUE THREAD

**Issue by Pradeep1308** [rtCamp/rtMedia#1835]
```
Environment :
WordPress Version: 5.9
BuddyPress Version: 10.0.0
rtMedia - pre-release branch
```

- [x] Default album is not visible to subscriber users. 

The Default album(Wall post) is not visible to the subscriber user. 

**Steps to reproduce:** 
Login to site as a non-admin user and navigate to <site-name>/members/<username>/media/albums and observe the issue. 

https://user-images.githubusercontent.com/44057535/153554969-3e33a04e-b2b5-4b20-8a3d-2f2b38a3459d.mp4

**Comment by thebengalboy** [comment]
@Pradeep1308  After releasing the core version, please take care of this issue.
