### ISSUE TITLE
Missing strings in Privacy Settings

### ISSUE THREAD

**Issue by thebengalboy** [rtCamp/rtMedia#1849]
**Describe the bug**
Some of the strings from Privacy settings are missing the POT file.

**To Reproduce**
Strings under: rtMedia→ Settings→ Privacy

**Expected behavior**
Those strings should be available in the POT file so that the user can Translate them.

**Screenshots or Visual**
![Missing strings](https://user-images.githubusercontent.com/5962216/156981379-98bfbb0f-42d7-45a3-9f90-0d24eb0802d8.png)

**Comment by kamalahmed** [comment]
I can fix this issue in 10-15 mins with testing. :) You can assign this to me bhai if you want.

**Comment by thebengalboy** [comment]
@kamalahmed Sure, thank you.

**Comment by kamalahmed** [comment]
Checked the code and tested everything and found the string is already translated on prerelease, maybe old verision of the translated file did not translate those strings. However, the texts are available in the .po file so it should be picked up by the translator.
