### ISSUE TITLE
Refactor Codebase

### ISSUE THREAD

**Issue by chandrapatel** [rtCamp/rtMedia#1859]
#### Move HTML to separate template files.

**File - `app/admin/RTMediaAdmin.php`**

- [ ] Move HTML from `install_transcoder_admin_notice()` to `transcoder.php` file in `app/admin/templates/notices/` folder.
- [ ] Move HTML from `rtmedia_premium_addon_notice()` to `premium-addon.php` file in `app/admin/templates/notices/` folder.
- [ ] Move HTML from `rtmedia_inspirebook_release_notice()` to `inspirebook-release.php` file in `app/admin/templates/notices/` folder.
- [ ] Move HTML from `rtmedia_addon_update_notice()` to `addon-update.php` file in `app/admin/templates/notices/` folder.
- [ ] Move HTML from `upload_filetypes_error()` to `upload-file-types.php` file in `app/admin/templates/notices/` folder.
- [ ] Move HTML from `rtmedia_update_template_notice()` to `update-template.php` file in `app/admin/templates/notices/` folder.
- [ ] Move HTML from `rtmedia_dashboard_widget_function()` to `right-now.php` file in `app/admin/templates/dashboard-widgets/` folder.
- [ ] Move HTML from `render_page()` to `main.php` file in `app/admin/templates/settings/` folder.
- [ ] Move HTML from `admin_sidebar()` to `sidebar.php` file in `app/admin/templates/settings/` folder.
- [ ] Move HTML from `render_admin_ui()` to `admin-ui.php` file in `app/admin/templates/settings/` folder.

**File - `app/admin/RTMediaFormHandler.php`**

- [ ] Move HTML from `types_content()` to `media-types.php` file in `app/admin/templates/settings/` folder.
- [ ] Move HTML from `sizes_content()` to `media-sizes.php` file in `app/admin/templates/settings/` folder.
- [ ] Move HTML from `render_option_content()` to `render-option.php` file in `app/admin/templates/settings/` folder.

#### Other Improvements

- [ ] Use `sprintf()` or `printf()` instead of concatenation `.` operator at following code lines. Also, review entire codebase and make this change wherever possible.
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L274
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L478-L480
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L775-L777
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L1360
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L1429
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L1769
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaFormHandler.php#L435-L436
- [ ] No need to escape static URLs.
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L1237
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L1279-L1288
  - https://github.com/rtCamp/rtMedia/blob/develop/app/admin/RTMediaAdmin.php#L2069-L2070
- [ ] https://github.com/rtCamp/rtMedia/blob/develop/app/helper/db/rt_plugin_info.php#L155 - Use `RTMEDIA_PATH` constant instead of using `realpath()` with `../../` file path. Replace that line with `$this->plugin_path = sprintf( '%s/index.php', untrailingslashit( RTMEDIA_PATH ) );` Also test this code.
- [ ] Following classes has empty construct method and don't have any properties or methods. If these classes not needed, then delete files.
  - https://github.com/rtCamp/rtMedia/blob/develop/app/helper/BPMediaBranding.php
  - https://github.com/rtCamp/rtMedia/blob/develop/app/importers/BPMediaBPActivityPlusImporter.php
- [ ] https://github.com/rtCamp/rtMedia/blob/develop/app/helper/RTMediaSupport.php#L186-L209 - Use [selected()](https://developer.wordpress.org/reference/functions/selected/) function instead of manually checking.

**Comment by thebengalboy** [comment]
@Pradeep1308 For this issue, we need to review the PR from @vishalkakadiya ; resolve the conflicts and merge them after QA.

**Comment by Pradeep1308** [comment]
All fixes are merged, hence closing the issue 👍
