### ISSUE TITLE
Issue observed on core plugin - [ code refactor] 

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#1866]
```
Environment: 
WordPress: v5.9.2
BuddyPress: v10.2.0
rtMedia: feature/refactor-code branch. 
```

---

- [ ] Accept Terms and services checkbox is not visible on the activity page. 

On the activity page, the checkbox for terms and services is not visible. 

Steps to reproduce: 
1. From the backend go to rtMedia - > Other settings and enable the show "terms and services" on the activity page. 
2. Navigate to the activity page and observe the issue. 

https://user-images.githubusercontent.com/44057535/160042507-33c988dc-911a-483d-9ac2-b581b0132510.mp4

---

- [ ] Modify image button is not working while editing the media. 

After clicking on modify image button the console error is displayed. `Uncaught ReferenceError: dc8ce3291a is not defined` error is displayed in the console. 

Steps to reproduce: 
1. Go to the media page and open any media. 
2. Click on edit and modify the image and observe the issue. 

https://user-images.githubusercontent.com/44057535/160044413-bbc0b32c-71d2-4c08-b791-746fae285106.mp4

---

- [ ] Buttons for pagination are not displayed on the media page. 

Steps to reproduce: 
1. From the backend go to rtMedia - > display and select "display media pagination" option as pagination. 
2. Navigate to the media page and observe the pagination. 

https://user-images.githubusercontent.com/44057535/160047070-af1134e3-1ae5-4324-b25b-757d3690f951.mp4

---

**Comment by vishalkakadiya** [comment]
@pavanpatil1 Those issues are fixed now, can you reverify them. Thanks!

**Comment by pavanpatil1** [comment]
Verified the issues, Fix is working fine. Hence closing this issue. 


https://user-images.githubusercontent.com/44057535/160343345-33b055f1-be26-4ef5-8c4a-40d46bf359a9.mp4
