### ISSUE TITLE
Enhancement w.r.t Share on Social Media Sidebar

### ISSUE THREAD

**Issue by Mukulsingh27** [rtCamp/rtMedia#1868]
### `Description`
Idea is that we can enhance the end-user UI/UX experience with respect to sharing on social media.

### `Solution`
We will give our end-users an interactive option in the admin panel.

`From this:`
![47](https://user-images.githubusercontent.com/54891099/160763991-e21a1739-9a7c-4a78-8d56-6f72cb99aed6.png)

`To this:`
![48](https://user-images.githubusercontent.com/54891099/160764084-fc1ad54d-4676-483b-b647-a8ac96e4731c.png)

**Comment by pooja-muchandikar** [comment]
@Mukulsingh27 

As discussed over call you can go ahead with following points:

- Button hover effect
- Icons shown for Title like the Share and Bell Icon for subscribe
- Button let me same as other existing buttons

**Comment by Mukulsingh27** [comment]
After the fix:

https://user-images.githubusercontent.com/54891099/160778474-9f08a3e0-6363-4b3b-a702-6663c8f225f7.mp4

Final result:
![1](https://user-images.githubusercontent.com/54891099/160778427-1586d3bf-f6ac-4225-8292-bb7049bb8d43.png)

**Comment by pavanpatil1** [comment]
Fixed in #1870. Hence closing this issue.
