### ISSUE TITLE
Post to Twitter Social-Button is not working

### ISSUE THREAD

**Issue by Mukulsingh27** [rtCamp/rtMedia#1869]
**Describe the bug**
- When a user wishes to share a status related to rtmedia on twitter then the button is not working and not allowing a user to pre-fill the data on Twitter status. 

**To Reproduce**
- Go to rtmedia admin panel
- Navigate to `spread-the-word` right sidebar
- Click on `Post on Twitter`

**Expected behaviour**
- On clicking the link, the user should redirect to the Twitter website with pre-filed status data related to rtmedia.

**Screenshots or Visual**

https://user-images.githubusercontent.com/54891099/160767043-84228f34-178a-4360-bf98-66551411de8d.mp4

**Test Environment Used**

- WordPress: v5.9.1
- BuddyPress: v10.1.0
- rtMedia: v4.6.10
- BP rewrites: v1.0.0-beta2

**Comment by pavanpatil1** [comment]
Verified the issue, Able to reproduce the issue. You can start working on it @Mukulsingh27..

**Comment by Mukulsingh27** [comment]
After the fix:

https://user-images.githubusercontent.com/54891099/161211252-d84ed774-e293-439f-9411-8eab737155d0.mp4

**Comment by pavanpatil1** [comment]
Fixed in #1874. Hence closing this issue.
