### ISSUE TITLE
Explore BP Rewrite Plugin 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1871]
We use some BuddyPress features in our Core rtMedia Plugin. And currently BuddyPress are going to release BP Rewrite Plugin. 
https://bpdevel.wordpress.com/2022/03/12/bp-rewrites-1-0-0-beta2/

Before this plugin is released we need to make sure this is compatible with our rtMedia Core and its add-ons. We did some initial testing and found out some [issues](https://github.com/rtCamp/rtMedia/issues?q=is%3Aissue+is%3Aopen+label%3ABP-rewrite-plugin). 

We need to fix these issues, but before that we need to understand the plugin thoroughly and then find out the root cause of the issues. 

- [x]  Understand the BP Rewrite plugin thoroughly and also go through BuddyPress plugin - @vishalkakadiya 
- [x] Find out all possible issues - @pavanpatil1 Task already available [here](https://github.com/rtCamp/rtMedia/issues/1852)
- [x] Find out the common issues and start debugging the issue to find the root cause - @vishalkakadiya 
- [x] We will first find the root cause and then work on the fixes

**Note: While fixing make sure we don't alter the existing BuddyPress features/components**

 Estimate for Understanding the BP Rewrite Plugin: [_Possibly could be fixed by 15th April but that may vary_]

**Comment by thebengalboy** [comment]
Related issues are here: https://github.com/rtCamp/rtMedia/issues?q=is%3Aissue+is%3Aopen+label%3ABP-rewrite-plugin

**Comment by thebengalboy** [comment]
Closing the issue as this has been completed.
