### ISSUE TITLE
Enhancement w.r.t file attachment in Support Form

### ISSUE THREAD

**Issue by Mukulsingh27** [rtCamp/rtMedia#1872]
### `Description`
Idea is that we can enhance the end-user UI/UX experience with respect to uploading an attachment on the support page.

### `Solution`
We will give our end-users an interactive option to drag and drop their attachment.

`From this:`
![3](https://user-images.githubusercontent.com/54891099/161009685-2fcd93f6-2b6e-4f04-bb2a-c63a3a01edf1.png)

`To this:`
![4](https://user-images.githubusercontent.com/54891099/161206210-f28bdcad-a5ac-44a6-a2bb-29877ba00073.png)

**Comment by Mukulsingh27** [comment]
With respect to the call held with Pradeep
- Drag and Drop is not possible to implement for now
- So for now we are just enhancing the attachment design
- Will try to implement it afterwards

**Comment by pavanpatil1** [comment]
Fixed in #1873. Hence closing this issue.
