### ISSUE TITLE
rtMedia edit buttons are breaking and not aligned properly

### ISSUE THREAD

**Issue by Rink9** [rtCamp/rtMedia#1875]
**Issue Description**
rtMedia edit buttons are breaking and not aligned properly

**Environment setup**

1. Activate any theme (eg: twenty twenty)
2. Activate buddyPress v10.2.0
3. Activate rtMedia for WordPress, BuddyPress and bbPress v4.6.10

------------------

**Issues:**

- [x] 1. `Save `and `back` button inconsistency

**Steps to reproduce**

1. Go through /members/admin/media/
2. Click on one of the image uploaded previously
3. Click on edit ( Here you can see the button inconsistency on `save` and `back`button

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/44554636/161222913-56a2148f-be4f-4d8e-b2ee-78643093f621.png">

**Expected behaviour**

Button should be consistent and aligned.

- [x] 2. `Modify image` button is aligned to other buttons

**Steps to reproduce**

1. Go through /members/admin/media/
2. Click on one of the image uploaded previously
3. Click on `Image` tab ( here you can view that modify button is aligned to image and other buttons )

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/44554636/161222580-2016bdc0-2cd5-4153-a8d6-4e19e0908779.png">

**Expected behaviour**

Button should be consistent and will not align to each other. `Modify image` button needs top and bottom padding

- [x] 3. `Undo `& `redo` button is not aligned

**Steps to reproduce**

1. Go through /members/admin/media/
2. Click on one of the image uploaded previously
3. Click on `Image` tab 
4. Scroll down and click on `modify image` button
5. Scroll up and view the `undo` & **redo** button ( Not consistent, aligned to top and also button background color is faded)

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/44554636/161222675-dbd6486a-d01b-4096-ab76-fb59a654ddcf.png">

**Expected behaviour**

1. Button background color will be #39414d
2.  Need top padding and will align on left
3.  After clicking on `modify image `button it scrolls down to bottom which is incorrect it should take on `rtmedia-single-edit-title-container` div

cc: @pooja-muchandikar

**Comment by Mukulsingh27** [comment]
@pooja-muchandikar 
All the above issues are resolved as mentioned by Lutfun, Just getting a small issue that is the back button is appearing small
Reason
- The size of both the `save` and the `back` button is the same in rtmedia-core plugin
- But both the buttons are mismatching in the size ( theme-dependent )
- Tried around 10 diff themes ( 5-6/10 buttons are appearing fine ) ( 3-4/10 buttons are mismatching )
