### ISSUE TITLE
Design issue in themes tab of rtmedia-admin

### ISSUE THREAD

**Issue by Mukulsingh27** [rtCamp/rtMedia#1876]
**Describe the bug**
- The **live-demo** and **buy** options are overlapping with the `themes-details` button.

**To Reproduce**
- Go to rtmedia admin panel
- Navigate to `themes` tab
- Hover on themes by rtCamp

**Expected behaviour**
- On clicking the link, the user should redirect to the Twitter website with pre-filed status data related to rtmedia.

**Screenshots or Visual**
![Screenshot from 2022-04-01 14-24-46](https://user-images.githubusercontent.com/54891099/161231796-3dc9aea9-13e8-48d1-a262-c882ae16a356.png)

**Test Environment Used**

- WordPress: v5.9.1
- BuddyPress: v10.1.0
- rtMedia: v4.6.10
- BP rewrites: v1.0.0-beta2

**Comment by Mukulsingh27** [comment]
After the fix:
![Screenshot from 2022-04-01 16-38-22](https://user-images.githubusercontent.com/54891099/161252900-86098788-0d12-42b8-8546-f8038aaa2cdc.png)

**Comment by pavanpatil1** [comment]
Fixed in #1877. Hence closing this issue.
