### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by Pradeep1308** [rtCamp/rtMedia#1884]
Multisite Issue
Undefined index: thumbnail
<img width="1452" alt="Screenshot 2022-04-11 at 11 23 01 AM" src="https://user-images.githubusercontent.com/61630284/162673286-2edf8408-8f13-4c4b-8968-33f6aef21a6d.png">

**Comment by pavanpatil1** [comment]
Fixed in https://github.com/rtCamp/rtMedia/pull/1885. Closing this issue
