### ISSUE TITLE
Post update is not working until it get's browser refresh

### ISSUE THREAD

**Issue by Rink9** [rtCamp/rtMedia#1893]
**Issue Description:**
Throwing a console error while posting anything, Without refresh can’t able to see post whenever clicked on `Post Update` button.

**Test Environment:**
WP 5.9.3
BuddyPress 10.2.0
rtMedia Core Pre-release branch
Theme 2020 and 2021

**Steps to reproduce**

- Activate rtMedia Core and BP plugin
- Go to Activity `page <site-name>/members/admin/`
- Do not enable `Allow upload from activity stream setting` from BuddyPress tab
- Note: Privacy setting is disabled
- Enter any text on the what’s new text area
- Click on post update button

**Actual result**  Observe that on click nothing happens. Reload the page the observe that the activity feed gets created.

**Expected result:** After clicking of post update button, post should create immediately

**Screenshot:** ![image](https://user-images.githubusercontent.com/44554636/163926032-e5ff2174-649a-4dfb-bd63-7a3f62d6a5fa.png)

**Comment by pooja-muchandikar** [comment]
@Pradeep1308 

Test Environment: 
WP 5.9.3
BuddyPress 10.2.0
rtMedia Core Pre-release branch
Theme 2020 and 2021


Steps: 

- Activate rtMedia Core and BP plugin
- Go to Activity page <site-name>/members/admin/
-  Do not enable Allow upload from activity stream setting from BuddyPress tab
- Note: Privacy setting is disabled
- Enter any text on the what’s new text area
- Click on post update button
- Observe that on click nothing happens 
- Reload the page the observe that the activity feed gets created

cc: @Rink9

**Comment by thebengalboy** [comment]
Closing the issue as the issue has been solved with the PR #1894
