### ISSUE TITLE
Video thumbnail not visible on Activity page

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1912]
Currently if someone is using only rtMedia Core then on uploading video file, the default thumbnail is shown on **/media** page. But on activity page thumbnail is not displayed, because of which it shows dark video. Refer the below screenshot. 

![image](https://user-images.githubusercontent.com/41000648/166236127-d46bd0f3-c9d2-4e06-970c-a1a6e946df2b.png)

---

We need to find a solution for same. 

Reference: https://rtmedia.io/ticket/2817504/

**Comment by pooja-muchandikar** [comment]
Hi @vishalkakadiya,

Can you please share update on this issue? Have you started working on same?

**Comment by pooja-muchandikar** [comment]
Alright Thanks @vishalkakadiya,

@Pradeep1308 please continue with this tasks taking the inputs from [here](https://github.com/rtCamp/rtMedia/issues/1912#issuecomment-1120910743)

**Comment by thebengalboy** [comment]
Closing the issue as this has been solved.
