### ISSUE TITLE
Test with BuddyPres 10.3.0 Maintenance Release

### ISSUE THREAD

**Issue by thebengalboy** [rtCamp/rtMedia#1918]
**Description**
BuddyPress released a new version today as part of the maintenance. Release note: https://buddypress.org/2022/05/buddypress-10-3-0-maintenance-release/

We need to test both the rtMedia Core and Premium with the latest version of BuddyPress. We need to find out if there is any functional or design break with the new version.

**Comment by pavanpatil1** [comment]
<h3>Update: </h3>

Tested the Core and premium plugin with the latest version of BuddyPress v10.3.0. Both the plugins are working fine. No blockers found.

**Comment by thebengalboy** [comment]
Closing the issue as this has been tested and working fine.
