### ISSUE TITLE
PHP notice displayed on Sitewide gallery albums page

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#1919]
```
Enviornment: 
WP-v6.0
BuddyPress- v10.3.0
rtMedia- v4.6.11
rtMedia-pro - v1.0.0
```

PHP notice is displayed on Albums page created from sitewide gallery.  Below notice is displayed. 

`wp-content/plugins/rtMedia/app/main/controllers/template/rtmedia-functions.php:1661`

https://user-images.githubusercontent.com/44057535/170485831-932785ea-159c-45c1-9773-35b640f7b51b.mp4

**Comment by Pradeep1308** [comment]
@pavanpatil1 This issue is not reproducible from my end as of now, can you please check on this again.

**Comment by pavanpatil1** [comment]
Verified the issue, Not able to reproduce the issue now. Closing this issue for now. 


https://user-images.githubusercontent.com/44057535/170976845-e833fcc4-45f4-470f-9213-b69f9cd28471.mp4
