### ISSUE TITLE
Update tested upto in WordPress.Org

### ISSUE THREAD

**Issue by thebengalboy** [rtCamp/rtMedia#1920]
**Description**
We need to update WordPress readme for both the Transcoder and rtMedia plugin and mentioned the plugin is tested up to WordPress version 6.0

- [x] Update `Tested Upto` for rtMedia
- [x] Update `Tested Upto` fro Transcoder

**Comment by pooja-muchandikar** [comment]
@thebengalboy Updated Tested upto version on both plugins.

**Transcoder:**

![image](https://user-images.githubusercontent.com/41000648/170937188-da2f0d7e-dd9c-4569-a399-08340f659f0e.png)

---

**rtMedia Core:**

![image](https://user-images.githubusercontent.com/41000648/170937275-056a122d-4517-4e8a-8486-319962c5f617.png)

---

**Comment by thebengalboy** [comment]
Thank you @pooja-muchandikar; Marking the task as completed and closing the issue.
