### ISSUE TITLE
On the group media page, the count for Album is displayed on the albums page but the album is not displayed. 

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#1922]
The count for the album is displayed but the album is not visible on the Group media page. If no media is added to the wall post album. 

Steps to reproduce: 
1. Create a new group and enable the media in the group. 
2. Go to the media page and Observe the issue. 

Expected result: If the count is visible then the album should be displayed. 

https://user-images.githubusercontent.com/44057535/172284593-28bc8aaf-d94f-4af5-89ce-210e1a6124e5.mp4

**Comment by thebengalboy** [comment]
@Pradeep1308 How much time it may take to get it solved? I feel like we should not release publicly having a known issue. We need to solve it even if we need to delay the release (_Unless the release is urgent_).

cc/ @pooja-muchandikar

**Comment by pooja-muchandikar** [comment]
@pavanpatil1 Few things to check:
- Album creation is done from Group or Profile page?
- If group then yes, the issue make sense and needs to be fixed as we are creating album and its not being displayed
- If the album is created from profile page, then its issue of showing the count on group page as well. As I suspect the count logic applied for profile page is getting applied to group page as well. In this scenario we need to handle it differently. 

Can you quickly check these points and let us know? This will help us to estimate the time to fix the issue. 

cc: @Pradeep1308

**Comment by pavanpatil1** [comment]
Below are the observations: 

> Album creation is done from Group or Profile page?

It is happening for the default album(Wall post) on the Group media page. If we add the media to the album then the album is visible properly. Just when there are no media present in an album at that time only it is happening.

**Comment by Pradeep1308** [comment]
The issue as of now is that, the count 1 is visible for album in group, but in the db there is no creation of album and the count is a dummy value that is showing in the frontend. 
cc: @thebengalboy @pooja-muchandikar @pavanpatil1
