### ISSUE TITLE
Replacing Addon with Premium

### ISSUE THREAD

**Issue by thebengalboy** [rtCamp/rtMedia#1923]
**Description**
As we have merged all the `addons` into Premium and no longer say/promote `addon` anywhere, we need to replace the `Addon` from the core/free plugin menu. Instead of `Addon`, would prefer to add `Premium`.

A reference prototype:
![Premium](https://user-images.githubusercontent.com/5962216/172372783-324134e4-3c3e-4553-9da3-ea546ef56f43.png)

**Comment by thebengalboy** [comment]
@pooja-muchandikar What do you think about the changes? We can do it with the coming release I think.

**Comment by thebengalboy** [comment]
@Pradeep1308 Can you show me how it looks?

**Comment by Pradeep1308** [comment]
This issue is resolved and PR is Merged.
