### ISSUE TITLE
Deactivation Reason: collecting user data while deactiving the plugin

### ISSUE THREAD

**Issue by thebengalboy** [rtCamp/rtMedia#1934]
**Description**
We want to collect feedback when the plugin is deactivated on the site. 

**What we will collect:**
- User email who deactivated the plugin
- Reason why deactivated
- Site URL

**Procedure:**
- We need to make an API call to rtMedia site to collect feedback.
- Display popup when user clicks on deactivate link of our plugin
- When users click on submit & deactivate, make an API call to our site to submit feedback and the plugin will be deactivated.
- We can make the API call in the plugin deactivation hook and plugin deactivation will be handled by WP itself.
- Create a custom database table that will store feedback on [rtMedia.io](http://rtmedia.io/) site and create a custom admin page to display those feedback in WP admin. It should have an export option in CSV.
- Additionally, add a yes/no question saying "Notify me about future updates and features" with neither option selected by default and let select by the user.

**Feedback Title**: If you have a moment, please let us know why you are deactivating:
**Feedback options:**
- I couldn't understand how to make it work
-  I found a better plugin
-  The plugin is great, but I need specific feature that you don't support
-  The plugin is not working
-  It's not what I was looking for
-  The plugin didn't work as expected
- Other (Other will have a text input field)

Example Prototype: https://prnt.sc/xnqHwpmctoLj

**Comment by robicse11127** [comment]
@chandrapatel @gagan0123 
After doing RND to find out how we can implement this feature into our plugin. I found out most of the plugins who are using this feature are using service from [Freeminus](https://freemius.com/) or [Appsero](https://appsero.com/) or somethings similar to this. Who are provides a SDK to integrate in the plugin or theme and track down the survey data with the popup and getting the used feedback when deactivating. 
So will we you the same for us? Please let me know your thoughts.
Thanks.
Cc: @thebengalboy

**Comment by thebengalboy** [comment]
Please note that we may not be able to afford a paid service for the time being. As a result, we need to seek an appropriate free choice.

**Comment by thebengalboy** [comment]
@robicse11127 Is there any drawback to the method suggested by @chandrapatel if we do not use a third-party service? What are the additional benefits of having a 3rd party service?

**Comment by robicse11127** [comment]
The benefit of using those services are...
- They provide SDK to integrate in the plugin which can be implemented easily and has customisable options from the code as we want.
- It has data driven dashboard which provides various reports about the plugin

And if we want to create from the scratch
- Currently we do not have API ready in the main site where that data will be submitted. 
- Also we need to finalise the API what we want to save and how.
- Then we can start working from the plugins end to send back the data where we want to store.
Cc: @thebengalboy

**Comment by thebengalboy** [comment]
@robicse11127 We can not go with Appsero, because it'll require moving the whole release process there. And I do not see Freeminus has a free package that can serve us. So, I assume building it on our own is the last option.

**Comment by robicse11127** [comment]
@pavanpatil1 @pooja-muchandikar 
Here we need to install the `rt-plugin-survey` plugin in the `rtmedia.io` site to have the stored survey data. Also in this plugin we have a settings page where we need to add the **administrator Username and Application Password** to be saved.
The Application Password can be generated from the the users profile showing in the below image
<img width="742" alt="image" src="https://user-images.githubusercontent.com/9913884/199228232-dc4f1188-c12e-405f-863b-4604f2947f54.png">

And in the **rtMedia plugin** we also need to update the API URL with the https://rtmedia.io
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/9913884/199228450-cfef4241-d906-4b56-81aa-0c2091d953b7.png">

**Comment by pooja-muchandikar** [comment]
@robicse11127 Thanks for the details!

@pavanpatil1 @Pradeep1308  please check this if its working as expected

**Comment by pooja-muchandikar** [comment]
@pavanpatil1 please cross check the functionality using rtMedia Core & use the plugin on rtMedia.io dev site and check if everything is working as expected.

cc: @aviral-mittal

**Comment by pavanpatil1** [comment]
Hi @robicse11127, verified the PR https://github.com/rtCamp/rtMedia/pull/1939, not able to submit the deactivation form. After clicking on submit button the console error is displayed. Also, there are a few conflicts in PR could you please check ?.



https://user-images.githubusercontent.com/44057535/215652393-925875ac-c9ee-4e05-a256-d3ba8bf569c7.mp4

**Comment by robicse11127** [comment]
It is been tested and code conflict merged.

**Comment by kjnanda** [comment]
@pavanpatil1 Please check my comment below.

- Clicking on `deactivate plugin button with selected reason from the given choice does not work as expected and shows the console js errors.

Please check this visual - 

https://github.com/rtCamp/rtMedia/assets/15173772/9d3d155c-3ebb-479e-8380-13abfd6985d9

- If I select `I rather wouldn't say` link - I'm able to deactivate the plugin but still has js console errors

Please check this snapshot - 
![image](https://github.com/rtCamp/rtMedia/assets/15173772/5da0299c-dfb6-443b-8cc5-b89d3c4970a8)

**Comment by Utsav-Ladani** [comment]
Hello @kjnanda,

I disable the `HTTP` authentication to test this feature on the dev site. Please enable it back after the testing. I also added some code changes to handle the error in [this](https://github.com/rtCamp/rtMedia/pull/1989) PR.

**Comment by kjnanda** [comment]
@Utsav-Ladani Kindly get this PR reviewed first. As after review it would need another round of testing.

Also, regarding http auth, I'm not clear why do we need to remove it?

CC @pavanpatil1

**Comment by Utsav-Ladani** [comment]
@kjnanda [this](https://github.com/rtCamp/rtMedia/pull/1989) PR is review now. you can test it.

We need to disable `HTTP` auth for testing because the `rtmedia-dev.rtm.rt.gw` site is protected with HTTP auth for security reasons, and our plugin deactivation survey is sent to this site. So if we want to test the plugin, we need to specify the password in the request, or we can test it by disabling it for a moment.

However, on the actual site `rtmedia.io`, we don't need anything because it doesn't have HTTP auth.

**Comment by kjnanda** [comment]
@Utsav-Ladani This is working as expected now.

**Comment by kjnanda** [comment]
Cross verified wrt dev branch and added fix working properly.

**Comment by kjnanda** [comment]
Tested after release and it works as expected.
