### ISSUE TITLE
.Org description update

### ISSUE THREAD

**Issue by thebengalboy** [rtCamp/rtMedia#1937]
**Description**
The following thing we need to update from the WordPress description

1. All the individual feature URLs pointing to our new feature page.
2. Replace all the `Addon` words with `feature/s`
3. If a feature is mentioned as `plugin`, replace that with `feature/s` as well.

**Comment by pooja-muchandikar** [comment]
This task is completed, readme.txt is updated and changes are pushed on `pre-release` branch. 

Also the changes are pushed to WP.ORG repo through SVN.
