### ISSUE TITLE
Error message is displayed in debug log for load more button

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#1945]
On click on load more button following error messages are displayed. 

`Error message: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /home/u914040766/domains/[beehive-media.com/public_html/wp-content/plugins/buddypress-media/app/main/RTMedia.php:186](http://beehive-media.com/public_html/wp-content/plugins/buddypress-media/app/main/RTMedia.php:186)`

```

Stack trace:
#4 /home/u914040766/domains/[beehive-media.com/public_html/wp-content/plugins/buddypress-media/app/main/RTMedia.php(1197)](http://beehive-media.com/public_html/wp-content/plugins/buddypress-media/app/main/RTMedia.php(1197)): RTDBUpdate->do_upgrade()
#5 /home/u914040766/domains/[beehive-media.com/public_html/wp-content/plugins/buddypress-media/app/main/RTMedia.php(975)](http://beehive-media.com/public_html/wp-content/plugins/buddypress-media/app/main/RTMedia.php(975)): RTMedia->update_db()
```

Note: Not able to reproduce the issue with the WP default theme. The above error is observed on the customer's site

Ref ticket: https://rtmedia.io/ticket/2848630/

**Comment by Pradeep1308** [comment]
Checked the issue and tried it reproduce it with different themes but I couldn't reproduce it.
The problem is specific to the customer theme.
