### ISSUE TITLE
Translation Issue: Privacy options are not getting translated

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1946]
We need to figure out why privacy options are not being translated. 

Privacy options are on activity page, media page, group activity, group media etc.,

![image](https://user-images.githubusercontent.com/41000648/191907795-7829e7ed-dade-4f2f-ad6a-374d70ad8ced.png)

Ticket: https://rtmedia.io/ticket/2852185/

**Estimate: 3hrs**

**Comment by robicse11127** [comment]
The translation functions are used correctly. It should work correctly...as others are working.
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/9913884/216264625-17e055f1-f445-4a07-9fa4-870a1c47ab29.png">
Translation texts are also added in the .pot file
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/9913884/216265072-1b04969d-7960-4648-9d62-dab2c53978fa.png">

**Comment by pooja-muchandikar** [comment]
@pavanpatil1 please test this ticket. If translation is working as expected.

**Comment by pavanpatil1** [comment]
Verified the translation. The other strings in the privacy dropdown are translating fine but the `public` string is still not translating. @robicse11127 could you please check ?

![image](https://user-images.githubusercontent.com/44057535/217443604-3950b834-8e32-4483-bd7a-a0de071d45be.png)

**Comment by robicse11127** [comment]
@pavanpatil1 Public is same in English and French. The difference is in pronunciation.
So the string is actually been translated
<img width="779" alt="image" src="https://user-images.githubusercontent.com/9913884/217516884-754e093f-b377-4f26-9cd3-e6ac8566bcbe.png">
Thanks

**Comment by pavanpatil1** [comment]
This is working as expected as per the above comments. Hence closing this issue for now.
