### ISSUE TITLE
Masonry cascading issue on scrolling

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1947]
When scrolling down the activity stream to the load more button, the page adds more content. Once the page adds more content, that’s when the overlapping occurs. 

Ticket: https://rtmedia.io/ticket/2852673/

On removing the codes from css, Masonry is now active. Following link might be useful in fixing the issue. 
https://masonry.desandro.com This was located in the rtmedia plugin next to the off and in switch. 

**Estimates: 4hrs**

**Comment by Pradeep1308** [comment]
Read the article and doesn't find anything new changes that can be done in our code.
Tried to reproduce the issue with default themes, but couldn't reproduce it,
