### ISSUE TITLE
[ Sidebar widget ] - Thumbnail for the image not visible properly

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#1963]
The thumbnail for the image is not visible properly. On the older theme the thumbnail looks broken. 

Note: ` .rtmedia-list-item>a .rtmedia-item-thumbnail img` class had extra CSS applied due to that this is occurring. 

**Possible solution:** Update the height to inherit. 

![image](https://user-images.githubusercontent.com/44057535/207283355-73cd11c1-7051-463c-92f0-8669400d7f4a.png)

**Comment by kjnanda** [comment]
@pavanpatil1 Is the issue is in front end or back end?

**Comment by kjnanda** [comment]
This seems to be working fine and added changes looks good to me. 

CC @pavanpatil1

**Comment by kjnanda** [comment]
Tested after release and it works as expected.
