### ISSUE TITLE
Make it possible to add ALT text to images before posting for blind and low vision comunity

### ISSUE THREAD

**Issue by AXSWeb** [rtCamp/rtMedia#1976]
Would it be possible to make it so people as they are posting an image, they can add ALT text. We need this for a blind and low vision comunity, so people with screen readers know what other members are posting.

**Comment by pavanpatil1** [comment]
Hi, 

It is possible, When media is uploaded from the activity page, the media name is used as the default alt text. To modify the alt text, you can simply edit the media and update its name, which will automatically update the alt tag accordingly.



https://github.com/rtCamp/rtMedia/assets/44057535/879c56b8-5bd3-4866-a783-841d1f2f80e8

**Comment by AXSWeb** [comment]
Hi, thanks for the info, I know you shared a video, but I am blind so it does not assist me. I really hoped I would not have to train the members on the website to rename their files, as I cannot rename the files, as I do not know what is in the image either. Guess I see how many complaints I get and then simply remove the plugin. Again thanks for the info.
