### ISSUE TITLE
Fix the spelling errors

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1984]
After making edits and saving the changes to any media, album, favlist etc it shows the message about successful operation completion. 

Please correct the spelling for `sucessfully` to `successfully`

------

<img width="1325" alt="Screenshot_2023-08-01_at_10_58_15_AM" src="https://github.com/rtCamp/rtMedia/assets/15173772/40cd3e74-0bb3-4992-ae03-8c7bb2f9c16a">

------

NOTE: _Please implement the required modifications to the script after the release._

**Comment by kjnanda** [comment]
@Utsav-Ladani please do the needful here.

CC @pavanpatil1

**Comment by Utsav-Ladani** [comment]
Change `sucessfully` to `successfully` in both the Core and Pro plugin. Here are the related PRs:

- https://github.com/rtCamp/rtMedia-Pro/pull/1376
- https://github.com/rtCamp/rtMedia/pull/1985

CC: @kjnanda, @pavanpatil1

**Comment by pavanpatil1** [comment]
Hi @Utsav-Ladani, Verified the fix and it is working fine. Please get the PR reviewed. 

![image](https://github.com/rtCamp/rtMedia/assets/44057535/377af81a-9025-43cc-a6ff-ff48f47918ae)

**Comment by kjnanda** [comment]
Cross verified wrt `pre-release branch` and added fix working properly.

**Comment by kjnanda** [comment]
Tested after release and it works as expected.
