### ISSUE TITLE
Fix deprecated notices with different PHP version

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1987]
There are many visible deprecated notices with different PHP versions.

- [ ] **PHP Version 8.2.8**

![image](https://github.com/rtCamp/rtMedia/assets/15173772/5218ee51-1fca-4eb6-9a85-f889906f1446)

-----

- [ ] **PHP Version 8.1.9** 

![image](https://github.com/rtCamp/rtMedia/assets/15173772/eca8281d-79ba-4688-9108-c59880db075b)

-----

- [ ] **PHP version 8.0.22**

![image (1)](https://github.com/rtCamp/rtMedia/assets/15173772/f898f504-5bbe-4bfd-b6c3-ed674781dde9)

----- 

## Test environment used:

```
1. Variable PHP versions as stated above
2. MySql - 8.0.16
3. Web server - ngnix  
4. WordPress Version - 6.2.2
```

**Comment by kjnanda** [comment]
@pavanpatil1 Please do the needful

**Comment by Utsav-Ladani** [comment]
Here is the [PR](https://github.com/rtCamp/rtMedia/pull/1988) to fix these deprecation errors. 

These changes work with all PHP 7.0 and later versions.

CC: @kjnanda, @pavanpatil1

**Comment by kjnanda** [comment]
@Utsav-Ladani I still see few deprecated errors on different pages from rtMedia plugin.

- [ ] **With PHP V8.2.8** 

On media page and On Phots | Music | Video  - 

https://github.com/rtCamp/rtMedia/assets/15173772/a8468c3d-6a4f-4c07-b4c1-6f654cba6f49

On media edit page - 
![image](https://github.com/rtCamp/rtMedia/assets/15173772/19b43d0f-1c6d-4ddf-943f-18abc9b41086)

-----

- [ ] **With PHP V8.1.9**

on media edit page - 
![image](https://github.com/rtCamp/rtMedia/assets/15173772/5d6177ad-a549-4b89-a6f3-4b353412bf36)

----

- [ ] **With PHP V8.0.22** - Everything looks fine ✅

**Comment by Utsav-Ladani** [comment]
Hello @kjnanda, I fix the above errors. Please check and let me know if there are any more.

**Comment by Utsav-Ladani** [comment]
Hello @kjnanda, I am not getting any deprecation errors with any version of PHP. These errors have been resolved in the current PR. But if it still persists, then please tell me how to reproduce the issue.

**Comment by kjnanda** [comment]
@Utsav-Ladani I will let you know in sometime.

**Comment by Utsav-Ladani** [comment]
@kjnanda, I fixed a few other errors. Please let me know if there are more errors.

**Comment by kjnanda** [comment]
@Utsav-Ladani This is fixed now.

**Comment by kjnanda** [comment]
I don't see any deprecated errors after fix in dev branch.

**Comment by kjnanda** [comment]
@pavanpatil1 I am getting the notice on every page of the website. This was not appearing before.

<img width="1314" alt="Screenshot 2023-08-11 at 1 12 46 PM" src="https://github.com/rtCamp/rtMedia/assets/15173772/04bbe5c2-d63a-4f22-824b-cea932934b2a">

Should I open a new issue and close this?

**Comment by kjnanda** [comment]
reported all the errors have been resolved post release.
