### ISSUE TITLE
Auto Static text - &nbsp; is added when uploading media before adding Text into textarea

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1991]
**Describe the bug**
When I upload media prior to adding the text, a static text element appears. This issue is consistent with the stable version of rtmedia.

The text is - `&nbsp;`

**Steps To Reproduce**
1. Go to activity page
2. Click on text area and click on uploader button.
3. Observe the text area , it will no longer be clickable.
4. Inspect the text area and change color of the text 
6. See the text is now visible.

**Expected behavior**
It should not add anything automatically to text area

**Screenshots or Visual**

https://github.com/rtCamp/rtMedia/assets/15173772/faa733ab-8629-4268-a242-cd002b59d917

------

**Note: This same for group too**

------

**Test Environment Used**
 - WordPress: V6.2.2
 - BuddyPress: V11.2.0  
 - rtMedia code from `pre-relase` , `dev` and `master` branch
 - Browser - Chrome - V115.0.5790.170

**Comment by pavanpatil1** [comment]
Fixed in the v4.6.17, Hence closing this issue
