### ISSUE TITLE
Group media page issue

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtMedia#2035]
Media files uploaded on group activity page are not visible on group media page. It should be visible. 

Steps to follow: 
1. Create a group and upload the image on the group activity page. 
2. Observe the media page. 

[group.webm](https://github.com/rtCamp/rtMedia/assets/44057535/fa49353f-8e03-4f23-a010-8966c605d3ff)

**Comment by Utsav-Ladani** [comment]
@pavanpatil1 issue is resolved, and PR is merged into `pre-release`. Please check and let me know if there is still something missing.

#### Dev note
> [!Important]
> - If newly added media are visible on the group media page but older ones are not, then we need to add migration with this plugin.
> - In migration, we have to change `groups` into `group` in the `context` column of table `wp_rt_rtm_media`.
> - The alternative way it to support both values in custom SQL query in code, but which increases the database query load.

**Comment by pavanpatil1** [comment]
It is fixed, Hence closing this issue
