### ISSUE TITLE
Video count is shown wrong after deleting a Video

### ISSUE THREAD

**Issue by maharrshi** [rtCamp/rtMedia#2050]
**Describe the bug**
The count of the video is shown wrong after deleting the video. When we go to top right corner in the front end

**Note:** 
Theme used: Twenty Twenty Three

**To Reproduce**
1. Go to wordpress Front end, top right corner and hover on the howdy, User.
2. Hover on the Media and click on the album option
3. Make sure a few videos are uploaded .
4. Observe the count of the video before deleting
5. Delete one of the video and observe the count of the Video to be shown as 0 instead of decrementing the count by 1

**Expected behavior**
Upon deleting the video, the count for the video should decrease by 1 without any page reload

**Actual behavior**
Upon deleting the video, directly the count is shown as zero and only when the page is reloaded the correct count is being shown

**Visual Representation**

https://github.com/rtCamp/rtMedia/assets/110522049/fe1c297b-2188-4274-a8af-4768211f311a

**Test Environment Used**
 - WordPress: [WP 6.6 Beta 2]
 - BuddyPress: [V 3.16.3]
 - rtMedia [V4.6.19]
 - Transcoder [v 1.3.6]
 - Wordpress beta tester [v 3.5.5]
 - Browser [Chrome v125]

**Additional context**

**Comment by pavanpatil1** [comment]
Released in v4.6.21. Hence closing this issue
