### ISSUE TITLE
Errors from rtmedia during document upload and edit

### ISSUE THREAD

**Issue by maharrshi** [rtCamp/rtMedia#2073]
**Describe the bug**
unable to edit a document

**To Reproduce**
1. Go to Media-> Documents
2. Upload a new document of type: pdf
3. observe the errors in the dev console: `Attempt to read property "media_author" on null` when start upload is pressed.
4. Observe the document count to be not updated when the new document is uploaded.
5. Edit the document 
6. See errors and warnings related to rtmedia plugin from the query monitor while saving the update.

**Expected behavior**
No error messages to be shown

**Screenshots or Visual**

https://github.com/user-attachments/assets/d3132a29-42eb-4307-96fc-f4ec990c1678

**Tested with :**
rtmedia: pre-release branch
rtmedia-pro: pre-release branch

**Comment by pavanpatil1** [comment]
Released in v4.6.21 hence closing this issue
