### ISSUE TITLE
oembed and page meta info for visualizing post updates

### ISSUE THREAD

**Issue by kwahlquist** [rtCamp/rtMedia#505]
I am currenlty torn between rtmedia and wpmu's buddypress activity plus.  Your solution seems to be supperior, as it already is integrated into albums for buddypress members and groups, however, it does not capture meta data from other sites when I post links.

Is there a plugin I am missing to get this basic requirement?  I am looking for more than just oembed, but actually facebook like capability that i will get pages meta titles and descriptions and bring back a great looking post update, rather than just a url being listed.

Is there any solution to this that integrates with rtMedia?  If not, do you have plans on integrating this into your current plugin?

**Comment by Ritesh-patel** [comment]
@kwahlquist this feature is covered in a premium add-on. Please check it here: https://rtcamp.com/products/rtmedia-activity-url-preview/
