### ISSUE TITLE
buddypress media page gives 404 error

### ISSUE THREAD

**Issue by jessijean** [rtCamp/rtMedia#509]
Hello. Our site keeps giving a 404 error when trying to access the media link on buddypress profile page. I have resaved permalinks multiple times and it isn't helping. Please advise on options to get this working again.
website www.altmodelamerica.com

**Comment by Ritesh-patel** [comment]
@jessijean I hope your issue has been resolved. Please check rtMedia support forum if you have any issue: http://community.rtcamp.com/c/rtmedia
