### ISSUE TITLE
Modal Windows Gallery View not working on IE10

### ISSUE THREAD

**Issue by maximus-meridius** [rtCamp/rtMedia#513]
Hello, 

we are on  rtMedia for WordPress, BuddyPress and bbPress 3.5.2.1 and when we upload images on IE10 and click on them to view the full resolution version we see the loading image # 1 etc... but then the screen doesn't display the image. 

SCRIPT5007: Unable to get property 'ownerDocument' of undefined or null reference 
jquery.js, line 3 character 15392
SCRIPT5007: Unable to get property 'ownerDocument' of undefined or null reference 
jquery.js, line 3 character 15392
SCRIPT5007: Unable to get property 'ownerDocument' of undefined or null reference 
jquery.js, line 3 character 15392

Attached is a screengrab

![screen shot 2014-02-04 at 12 52 24](https://f.cloud.github.com/assets/5479186/2076112/822a78d6-8d9b-11e3-83a8-3c887a7d6c94.png)

**Comment by Ritesh-patel** [comment]
Hi @maximus-meridius 

I hope your issue must be resolved by now. if not, please create a support topic on rtMedia support forum: http://community.rtcamp.com/c/rtmedia
