### ISSUE TITLE
Preview uploads

### ISSUE THREAD

**Issue by speedkid18** [rtCamp/rtMedia#514]
Hi Guys,

I've recently updated to version 3.6 of my favorite plugin rtMedia for WordPress, BuddyPress and bbPress. Since then when I want to upload eg a picture it works but it shows no preview or any indication that the file has been attached. When I click Post Update the file is attached. So it works, just that if you don't it will work you will attach the file multiple times without seeing any effect until you publish...

Is that just my set up or a common thing? I use Buddypress default theme. Edit: and Buddypress v1.9.2

Thanks!

**Comment by Ritesh-patel** [comment]
File preview is changed in rtMedia 3.8 and hence closing this one.
