### ISSUE TITLE
Problem with Russian translation rTMedia

### ISSUE THREAD

**Issue by nomad48** [rtCamp/rtMedia#571]
You have problems with Russian translation, there are errors in the code that indicates the translation. For example: look screenshot, check please, after every update, you need to manually update all. I added some translation in .po file. and your code can use to test and fix! With respect, Andrey.
![2014 10 22-14 32 05](https://cloud.githubusercontent.com/assets/9349934/4734697/0139d330-59d7-11e4-824a-70d2e2875b44.png)
![2014 10 22-14 33 35](https://cloud.githubusercontent.com/assets/9349934/4734698/01931a76-59d7-11e4-98f6-37cc04d41e0b.png)
![2014 10 22-14 17 51](https://cloud.githubusercontent.com/assets/9349934/4734653/7c4baf18-59d6-11e4-81f2-e84ecf15c1c9.png)
ps I have a full translation of the Russian language, rTMedia where to throw?

**Comment by nomad48** [comment]
Good day guys, I found a bug in PHP code, please for future updates. 
#: app/main/controllers/template/rt-template-functions.php:2125
#: app/main/controllers/template/rt-template-functions.php:2129
on these lines, there is no reference to the translation of ' rtmedia '
![10-01-2015 23-07-30](https://cloud.githubusercontent.com/assets/9349934/5693061/2ade5f4a-991e-11e4-8913-f920dfdec205.jpg)

**Comment by sanketio** [comment]
Thank you very much for pointing this out. It'll be fixed in future release of rtMedia.

Thank you.

**Comment by Ritesh-patel** [comment]
Hi @nomad48 

These issues has been fixed.
