### ISSUE TITLE
Issue with media being displayed on the activity feed of buddypress

### ISSUE THREAD

**Issue by avribijon** [rtCamp/rtMedia#601]
Hello I'm using rt for a youth center badge wordpress (badgelab.org). We're having an issue with the media thats upload in the buddy press activity space and the group activity space showing up. It worked when we first installed the plugin but now all its embedded is soundcloud links. 

I made the activity open on the site so that you can take a look at it. Email me at avricoleman@gmail.com for test admin login account. 

Thank you for your help in advance.

**Comment by Ritesh-patel** [comment]
Hi @avribijon,

Please check it once with WordPress default theme and other plugins disabled. It might be theme issue or a plugin conflict. 

It will be more helpful if you create support request at rtMedia support forum: http://community.rtcamp.com/

**Comment by avribijon** [comment]
It still didn't work with default theme, I updated the plugin and the
picture thumbnail works but uploading songs or sound isn't. Can you take a
look at it? badgelab.org

On Tue, Jan 27, 2015 at 2:03 AM, Ritesh Patel <notifications@github.com>
wrote:

> Hi @avribijon <https://github.com/avribijon>,
>
> Please check it once with WordPress default theme and other plugins
> disabled. It might be theme issue or a plugin conflict.
>
> It will be more helpful if you create support request at rtMedia support
> forum: http://community.rtcamp.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtCamp/rtMedia/issues/601#issuecomment-71604993>.
>



-- 
Avri Coleman
Commonwealth Foundation
http://www.commonwlth.org
avri@commonwlth.org
