### ISSUE TITLE
Default privacy settings bug

### ISSUE THREAD

**Issue by adrienko** [rtCamp/rtMedia#611]
Hi, 

I checked in the privacy settings for user as default the "member view" 
and when I connect as a member and go to privacy setting the default one is "public"

thanks a lot 

for you help 

best regards

Adrien K

**Comment by pranali333** [comment]
Hi Adrien K,

Make sure you are using latest version of rtMedia.

We have checked this on our demo site  http://demo.rtcamp.com/rtmedia   and it is working fine.

Thank you.
