### ISSUE TITLE
Sync BuddyPress activity favorites with rtMedia likes

### ISSUE THREAD

**Issue by Ritesh-patel** [rtCamp/rtMedia#614]

**Comment by rhisss** [comment]
Buddypics (another media / album / photo plugin for Buddypress, compatible with WP 4.1 Multisite and BP 2.2) uses the following code to show Favorit button in individual photo pages and it works. <code>					<?php if ( is_user_logged_in() ) : ?>
						<?php if ( !bp_get_activity_is_favorite() ) : ?>
							<a href="<?php bp_activity_favorite_link(); ?>" class="fav" title="<?php _e( 'Mark as Favorite', 'buddypress' ) ?>"><?php _e( 'Favorite', 'buddypress' ) ?></a>
						<?php else : ?>
							<a href="<?php bp_activity_unfavorite_link(); ?>" class="unfav" title="<?php _e( 'Remove Favorite', 'buddypress' ) ?>"><?php _e( 'Remove Favorite', 'buddypress' ) ?></a>
						<?php endif; ?></code>

**Comment by thebengalboy** [comment]
BuddyPress favorites and rtMedia likes are two different things. One can make a post favorite, that post might not have any media. Where the rtMedia likes are for the media only.

We are closing this issue for now.
