### ISSUE TITLE
Media doesnot show photos on Buddyprofile page

### ISSUE THREAD

**Issue by jao39** [rtCamp/rtMedia#619]
Dear Sir,

I wanted to try your nice RT media wordpress plugin.

I encountered a small problem. When I clicked on Media tab in BuddyPress profile in http://www.haadai.com/members/sample_achitect/ . It leads to a blank page.

I hope that you could help me out so that we can use your nice Plugin here.

Thank you in advance.
Pariya

**Comment by Ritesh-patel** [comment]
Hi @jao39 

Please check your server error logs if it leads to blank page. Also, check once with WordPress default theme and other plugins disabled, it might be a theme issue or some other plugin conflicting with rtMedia.

You can create a support request on rtMedia support forum: http://community.rtcamp.com/c/rtmedia
