### ISSUE TITLE
Dashboard Tabs not working

### ISSUE THREAD

**Issue by Dara1102** [rtCamp/rtMedia#639]
I have installed rtmedia and the verticle tabs are not working in the rtmedia Settings (Buddypress, Types, Media Sizes, Privacy, etc.)  None of the verticle tabs work under Addons, or Themes. 

I am running: 
rtmeda - 3.8.6
buddypress - 2.3.2.1
wordpress - 4.2.2
Theme is TrueMAG

Anyone else experiencing this issue?

**Comment by Dara1102** [comment]
After testing other plugins, found that it is a confllict with bp-cover.  Any resolution?

Thanks.

**Comment by Ritesh-patel** [comment]
Hi @Dara1102 

It's a CSS conflict with BuddyPress cover plugin and we have fixed it in rtMedia in 80569d59ffff0c9a8d01f78fb7274ce5ec173b09 commit.

It will be available in next release of rtMedia.
