### ISSUE TITLE
error with rt media settings

### ISSUE THREAD

**Issue by kiatyong812** [rtCamp/rtMedia#640]
Hi, the tabs on the left (i.e. buddypress, types, etc...) doesn't seem to work. Please help.

![image](https://cloud.githubusercontent.com/assets/13116228/8427923/947452d8-1f4d-11e5-8936-a1318e81c337.png)

**Comment by Ritesh-patel** [comment]
Hi @kiatyong812 

We just discover a CSS conflict with BuddyPress Cover plugin in rtMedia admin settings and have fixed it. If you use BuddyPress Cover plugin than this issue will be fixed in next update of rtMedia.

**Comment by kiatyong812** [comment]
Hi Ritesh, may i know when will the next update be?
