### ISSUE TITLE
 Rt media not working and media page not working.

### ISSUE THREAD

**Issue by roping** [rtCamp/rtMedia#694]
Hi, I have issues,if I upload to wall posts within actual media gallery, they get uploaded.But not showing in activate feed.Also,When i click in media from dashboard menu then i am showing "page not found" ..Please help me.

Thanks

**Comment by kiranpotphode** [comment]
Hi roping, 
We have already replied to your query at http://community.rtcamp.com/t/multisite-activity-stream/6805/6?u=kiranpotphode

We are closing this issue.
