### ISSUE TITLE
Add file type support for ".gifv" files

### ISSUE THREAD

**Issue by darrenfulton** [rtCamp/rtMedia#749]
Add support for .gifv.

Example file:
http://i.imgur.com/wYQHyZL.gifv

**Comment by mangesh** [comment]
@darrenfulton 
Thank you for the suggestion. We will discuss add the support for the .gifv files in the future release.

**Comment by Pradeep1308** [comment]
GIFV is the GIF video with high quality that has no sound like the normal videos. Just like a normal GIF, the GIFV also plays in loops forever until the user stops it. It uses the same functionality as GIF. GIFV project was introduced by the Imgur a few years ago. It was for automatically converting the uploaded GIF files into the WebM or MP4 video formats. They implemented the video in such a way that it looks and behaves just like a GIF. **GIFV is not really a file format, users will only be able to find this on websites like Imgur.**

You can read [here](https://appuals.com/gifv-and-gif-files/) more about it.
