### ISSUE TITLE
Happy Face Icons

### ISSUE THREAD

**Issue by DamnDramaQueen** [rtCamp/rtMedia#844]
Hi, 

This is my first timer putting request in, hope is right? 

I would like to suggest a new feature be added for the rtmedia lightbox comment box. Currently the comment box only do writing and do not have icons. NOT the emoji I am talking about. 

This is an i.e icons would like. birthday cake, smilely, gift, teddy bear. heart, etc etc. 

People would like to insert icons along when making comments. Who doesn't? 
 
![icons](https://cloud.githubusercontent.com/assets/25953389/24520987/6fc91628-1558-11e7-9a26-f45445c01a25.JPG)

Please send reply notification or if any update for this feature. 

Thanks

**Comment by robicse11127** [comment]
@aviral-mittal It is in progress.... Configuring the Emojies on the lightbox comment area.

**Comment by kjnanda** [comment]
@pavanpatil1 Added emoji support works fine but still there is scope of improvement.

<img width="362" alt="Screenshot 2023-08-07 at 12 00 25 PM" src="https://github.com/rtCamp/rtMedia/assets/15173772/b8ded2d3-481e-4340-ab89-2340de19a5b7">

- emoji icon size is uneven
- spacing seems not uniform
- currently, we are only showing limited emoji. The requested emoji icons seems not been added.

**Comment by Utsav-Ladani** [comment]
Raised [this](https://github.com/rtCamp/rtMedia/pull/1990) PR to resolve this issue. Please check and let me know if there is any issue.

CC: @kjnanda, @pavanpatil1

**Comment by kjnanda** [comment]
@Utsav-Ladani We can give scroll event for emoji inside the child panel instead of whole parent window. This does not give good UX.

**Comment by Utsav-Ladani** [comment]
I had fixed the UI, but this distortion is coming from `emoji-picker.js` minified files. I didn't find the source code of this minified file. So we have to create our custom library or use an existing third-party library. I will let you know once it is finalized and the issue is fixed.

**Comment by kjnanda** [comment]
@pavanpatil1 Please refer to comment added by Utsav ☝🏻

**Comment by pavanpatil1** [comment]
Hi @kjnanda @Utsav-Ladani, I have checked this and the scroller in the emoji picker seems to be fine now. We can merge the PR in pre-release


https://github.com/rtCamp/rtMedia/assets/44057535/eb689aac-e311-4505-a8a8-cc217d4e8146

**Comment by kjnanda** [comment]
@pavanpatil1I've verified this problem on an iPhone, and it's not functioning as intended. The emoji picker is not triggering any scroll events. Do we are still want to progress with know bug?

**Comment by Utsav-Ladani** [comment]
I made a few changes yesterday. It is working fine for me on Android. Please check and let me know if something not working.

**Comment by kjnanda** [comment]
Tested after release and it works as expected.
